import Image from "next/image";
import Link from "next/link";
import { Reveal } from "./Reveal";
import { SectionMeta } from "./SectionMeta";

// FV-539 — the visualization differentiator section, compressed. KC
// direction 2026-09-01: the FV-534 long-form version was "way too verbose
// for the home page"; the full research story (with citations) moved to
// /resources/does-visualization-work-for-athletes and this section now
// carries KC's own copy verbatim (headline triple, lede, three blocks)
// plus one pointer link to the article. Research claims live in the
// article under docs/content-evidence-standards.md; this section makes
// product and identity statements only. Still deliberately carries NO
// /signup CTA: the homepage's 4-CTA cadence is test-pinned (homepage-ia)
// and the after-sample CTA sits immediately above. The article link is
// the section's single link (also test-pinned).

const blocks = [
  {
    name: "See your game, not a highlight reel.",
    body: "Choose up to three plays from your sport and role. A voice guides you through the cues, movement, and decisions that matter, one play at a time.",
  },
  {
    name: "Practice the response.",
    body: "You picture a hard moment too, then rehearse the breath, truth, and next action that help you return to the play.",
  },
  {
    name: "Remember what does not change.",
    body: "Your identity is secure in Christ before the result. Ask for His strength, then compete without making performance prove your worth.",
  },
];

export function Visualization() {
  return (
    <section
      id="visualization"
      className="relative overflow-hidden isolate py-12 sm:py-20 md:py-28 scroll-mt-20"
    >
      {/* FV-537: darkened atmospheric background — locker-room image,
          AI-generated by KC (2026-08-31, no third-party license), master
          committed with his asset push and optimized to 871x1600 JPEG.
          Treatment is deliberately heavy: the image runs at low opacity
          under two onyx gradients so it reads as atmosphere, the garbled
          phone UI and brand marks in the source are illegible, and every
          text token keeps AA contrast over the brightest composited
          areas (cinderblock wall). Decorative: empty alt + aria-hidden
          wrapper, lazy (below the fold), same -z-10/isolate layering as
          the Hero's washes. */}
      <div className="absolute inset-0 -z-10 pointer-events-none" aria-hidden>
        <Image
          src="/images/backgrounds/viz-lockerroom.jpg"
          alt=""
          fill
          sizes="100vw"
          className="object-cover object-[center_32%] opacity-30"
        />
        <div className="absolute inset-0 bg-gradient-to-b from-onyx via-onyx/60 to-onyx" />
        <div className="absolute inset-0 bg-gradient-to-r from-onyx via-onyx/40 to-transparent" />
      </div>
      <div className="mx-auto max-w-[1240px] px-5 sm:px-8">
        <Reveal>
          <SectionMeta num="01" label="The mental rep" />
        </Reveal>
        <Reveal>
          <div className="grid gap-x-16 gap-y-6 sm:gap-y-10 items-end mb-10 sm:mb-14 grid-cols-1 lg:grid-cols-[1.05fr_0.95fr]">
            {/* KC's stacked headline triple (2026-09-01), verbatim. The
                trailing space inside the first two spans keeps the h2's
                textContent readable as one sentence run for tests and
                assistive tech; `block` display eats it visually. */}
            <h2 className="fv-h-section">
              <span className="block">Picture the play. </span>
              <span className="block">Prepare for pressure. </span>
              <span className="block">
                Compete from Christ&rsquo;s strength.
              </span>
            </h2>
            <p className="fv-lede">
              From Victory brings all three into one guided pregame session,
              built around your sport, your role, and what you need before
              you compete.
            </p>
          </div>
        </Reveal>

        <Reveal>
          <div className="grid grid-cols-1 sm:grid-cols-3 border-t border-b border-hairline mb-8 sm:mb-12">
            {blocks.map((block, i) => (
              <div
                key={block.name}
                className={`px-5 py-6 sm:px-7 sm:py-9 transition-colors duration-base ease-out hover:bg-onyx ${
                  i < blocks.length - 1
                    ? "sm:border-r border-hairline max-sm:border-b max-sm:border-hairline"
                    : ""
                }`}
              >
                <h3 className="font-heading font-semibold text-[22px] tracking-[-0.01em] text-cream m-0 mb-2.5">
                  {block.name}
                </h3>
                <p className="font-body text-[14px] leading-[1.55] text-cream/70 m-0">
                  {block.body}
                </p>
              </div>
            ))}
          </div>
        </Reveal>

        {/* The section's one link — the research story, told honestly
            (citations, limits), lives in the article (FV-539). Not a
            conversion CTA; the 4-CTA /signup cadence is unaffected. */}
        <Reveal>
          <p className="font-body text-[15px] leading-[1.6] text-center m-0">
            <Link
              href="/resources/does-visualization-work-for-athletes"
              className="text-gold underline underline-offset-2 hover:text-gold-bright transition-colors duration-fast"
            >
              Read: Does visualization actually work? &rarr;
            </Link>
          </p>
        </Reveal>
      </div>
    </section>
  );
}
