// Baseball positive-play VIZ library (FV-424) — 28 athlete-chooseable
// rehearsal scenarios, 7 per position (Pitcher/Catcher/Infield/Outfield).
// Authored by the content trio, verified by baseball-expert, KC prose-gated
// 2026-08-10. The FV-144 model: the athlete picks up to 3 of these and
// resolvePlaylist() plays them IN PLACE of the flagship viz-{role} clip
// (flagship = fallback). Registered in components/pregame/positive-plays.ts;
// the sport stays DORMANT (not in SUPPORTED_SPORTS) until the FV-100 gate.
// Prose source of truth: docs/scripts/baseball.md ("VIZ Clips — Positive
// Plays") — the book wins at render time (FV-302).

import type { AudioScript } from "./types";
import { SCRIPT_INSTRUCTIONS, VISUALIZATION_INSTRUCTIONS } from "./instructions.ts";
import { CLIP_LOUDNORM_FILTER } from "./loudnorm.ts";

// Baseball · Pitcher · attack-first-inning (viz play)
export const CLIP_VIZ_BSB_PITCHER_ATTACK_FIRST_INNING_SCRIPT: AudioScript = {
  slug: "viz-bsb-pitcher-attack-first-inning",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself taking the mound for the first inning, focused on the first pitch.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You toe the rubber, get your sign, and come set.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "First pitch, fastball at the knees on the glove-side corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your catcher receives it on the edge. Strike one.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get the ball back and prepare the same way.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Another fastball down produces early contact.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Ground ball to short. One out.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You keep the same tempo, get the sign, and hit the next target.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You finish the inning by working ahead and staying on your locations.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Baseball · Pitcher · strikeout-sequence (viz play)
export const CLIP_VIZ_BSB_PITCHER_STRIKEOUT_SEQUENCE_SCRIPT: AudioScript = {
  slug: "viz-bsb-pitcher-strikeout-sequence",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself facing a hitter with a clear plan for the at-bat.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "First pitch, fastball in for a strike. He takes it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You come back with another fastball on the outside edge. 0-2.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You show a breaking ball below the zone without leaving it over the plate.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He takes it. The count moves to 1-2.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He has seen firm pitches on both sides of the plate.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You go back to the breaking ball, finishing it down and away.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He starts his swing and misses over it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Strike three. You changed speed and location to finish the at-bat.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Baseball · Pitcher · escape-the-jam (viz play)
export const CLIP_VIZ_BSB_PITCHER_ESCAPE_THE_JAM_SCRIPT: AudioScript = {
  slug: "viz-bsb-pitcher-escape-the-jam",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself with runners on first and second, one out, looking for a ground ball.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You step off, take a breath, and get your sign.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stay with the plan instead of expanding the zone for a strikeout.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You throw the sinker at the bottom of the zone.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The hitter rolls it over sharply to short.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The shortstop feeds second, and the turn goes over to first.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The defense turns two. The inning is over.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The pitch location created the contact you wanted.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You execute the pitch and let the defense finish the play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Baseball · Pitcher · hold-and-field (viz play)
export const CLIP_VIZ_BSB_PITCHER_HOLD_AND_FIELD_SCRIPT: AudioScript = {
  slug: "viz-bsb-pitcher-hold-and-field",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself with a fast runner on first, holding him close and staying in your delivery.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You come set, eyes on the runner, then back to the mitt.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You vary your hold time, keep him close, then deliver.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stay quick to the plate without rushing your delivery.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The hitter chops it right back at you, a comebacker.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You field it clean, glove to hand.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You turn, set your feet, and make the feed to second.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The turn goes over to first. Two outs.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You control the runner, field the comebacker, and start the 1-6-3 double play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Baseball · Pitcher · putaway-pitch (viz play)
export const CLIP_VIZ_BSB_PITCHER_PUTAWAY_PITCH_SCRIPT: AudioScript = {
  slug: "viz-bsb-pitcher-putaway-pitch",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself ahead 0-2, ready to finish the sequence.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The first two pitches have him timed for the fastball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You come set and keep the same tempo in your delivery.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Changeup \u2014 fastball arm speed from the same release window.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "It finishes below the barrel.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He is out in front and swings over it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Swing and miss. Strike three.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your arm speed stays consistent and the pitch finishes below the zone.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You complete the sequence without changing or rushing your delivery.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Baseball · Pitcher · deep-outing-rhythm (viz play)
export const CLIP_VIZ_BSB_PITCHER_DEEP_OUTING_RHYTHM_SCRIPT: AudioScript = {
  slug: "viz-bsb-pitcher-deep-outing-rhythm",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself in the sixth inning, keeping your delivery repeatable.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The pitch count is climbing, so you check your breathing and posture.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get the ball, take the sign, and keep your normal tempo.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Fastball down, ground ball, one out.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Two pitches later, a routine fly ball. Two outs.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You use movement and location instead of reaching for more velocity.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stay tall, repeat your delivery, and hit the target.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The inning ends, and you return to the dugout.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You finish the inning with the same tempo and mechanics you started with.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Baseball · Pitcher · bounce-back (viz play)
export const CLIP_VIZ_BSB_PITCHER_BOUNCE_BACK_SCRIPT: AudioScript = {
  slug: "viz-bsb-pitcher-bounce-back",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself on the mound after a fastball catches too much plate and leaves the park.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The run counts. That pitch is finished.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You take the new ball, step behind the mound, and review the missed location.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You settle your breathing and return to the rubber.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The next hitter steps in. You get the sign and return to your plan.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You come set and repeat your normal delivery.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Fastball at the bottom of the zone, into the mitt. Strike one.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The catcher returns the ball, and you prepare for the next pitch.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You are back in the at-bat, ahead 0-1.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Baseball · Catcher · frame-the-zone (viz play)
export const CLIP_VIZ_BSB_CATCHER_FRAME_THE_ZONE_SCRIPT: AudioScript = {
  slug: "viz-bsb-catcher-frame-the-zone",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself set up low, giving the pitcher a quiet target.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The pitcher comes set and works to your glove.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The pitch comes to the low corner, right on the edge.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You receive it softly, keeping your body and glove quiet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You hold the pitch on the edge long enough for the umpire to see it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The umpire calls strike one.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You return the ball and reset your target.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "On the next borderline pitch, you receive from the ground up without extra movement.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You give the umpire a clean look at each pitch on the edge.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Baseball · Catcher · block-in-the-dirt (viz play)
export const CLIP_VIZ_BSB_CATCHER_BLOCK_IN_THE_DIRT_SCRIPT: AudioScript = {
  slug: "viz-bsb-catcher-block-in-the-dirt",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself calling for the breaking ball with a runner on third.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You give the sign, settle your weight, and prepare to block.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The pitch short-hops the dirt in front of you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You drop your hips behind it, chin tucked, glove between your knees.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball hits your chest protector and stays close.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You keep it directly in front of you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The runner stays at third.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You recover the ball, get to your feet, and check the runner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your block keeps the pitch close and prevents the advance.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Baseball · Catcher · throw-out-the-runner (viz play)
export const CLIP_VIZ_BSB_CATCHER_THROW_OUT_THE_RUNNER_SCRIPT: AudioScript = {
  slug: "viz-bsb-catcher-throw-out-the-runner",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself with a runner taking an aggressive lead at first.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stay balanced in your crouch and keep the runner in view.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The pitch comes in at the top of the zone, where you can handle it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The runner breaks for second. You receive the pitch cleanly.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You transfer close to your body as you replace your feet underneath you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You use a short arm action and carry the throw to the bag.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball arrives knee-high on the fielder's glove side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The shortstop applies the tag. Out.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The exchange, footwork, and accurate throw complete the play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Baseball · Catcher · call-the-game (viz play)
export const CLIP_VIZ_BSB_CATCHER_CALL_THE_GAME_SCRIPT: AudioScript = {
  slug: "viz-bsb-catcher-call-the-game",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself guiding the pitcher through the lineup from behind the plate.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The pitcher looks in, and you return to the plan for this hitter.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You notice where the hitter is late and which pitch he is tracking well.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You give the sign and set a clear target.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Fastball in, then an off-speed pitch away.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The change in speed keeps the hitter from getting on time.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He rolls a ground ball to the infield for an out.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You return the ball, check the situation, and call the next pitch.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You keep the plan clear and work with the pitcher one pitch at a time.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Baseball · Catcher · play-at-the-plate (viz play)
export const CLIP_VIZ_BSB_CATCHER_PLAY_AT_THE_PLATE_SCRIPT: AudioScript = {
  slug: "viz-bsb-catcher-play-at-the-plate",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself with a runner trying to score from second and the throw headed home.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "A base hit reaches the outfield, and the runner rounds third.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You move toward the plate, keep the runner's lane open, and track the throw.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The throw comes in on one hop, and you follow it into your glove.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You receive it cleanly, then move into position for the tag.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You apply the tag to the front edge of the slide.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The umpire calls the runner out at the plate.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You keep control of the ball through the tag.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You receive the throw, apply the tag, and record the out.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Baseball · Catcher · clutch-at-bat (viz play)
export const CLIP_VIZ_BSB_CATCHER_CLUTCH_AT_BAT_SCRIPT: AudioScript = {
  slug: "viz-bsb-catcher-clutch-at-bat",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself stepping into the box with a runner on second.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You take the sign, settle in, and stay with your approach.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The first pitch catches the edge for strike one. You stay with the plan.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The next pitch is a fastball over the outer half.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stay through it and drive it the other way.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball carries on a line into the right-center gap.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The runner scores as you round first and read the outfield.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You reach second standing with the ball back in the infield.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stay on the pitch and drive the runner home.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Baseball · Catcher · bounce-back (viz play)
export const CLIP_VIZ_BSB_CATCHER_BOUNCE_BACK_SCRIPT: AudioScript = {
  slug: "viz-bsb-catcher-bounce-back",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself right after a pitch skips past you to the backstop.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The runner advances. The play is over.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You retrieve the ball, return it, and reset your equipment.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You take one breath and settle back into your crouch.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You give the sign and present a firm target.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The next pitch is a breaking ball down in the dirt.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get your body behind it and keep it in front.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You recover the ball and return it to the mound.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You settle back into your crouch for the next sign.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Baseball · Infield · turn-two (viz play)
export const CLIP_VIZ_BSB_INFIELD_TURN_TWO_SCRIPT: AudioScript = {
  slug: "viz-bsb-infield-turn-two",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself ready for a double-play ball with a runner on first.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "With less than two outs, you set at double-play depth.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball is chopped on the ground into your range.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You field it out front and work your feet toward second.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You deliver a firm, chest-high feed to the bag.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your teammate touches second and makes a quick transfer.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The throw travels across the diamond on a line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "It reaches first ahead of the runner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You field the ball cleanly, deliver the feed, and the defense turns two.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Baseball · Infield · backhand-hole (viz play)
export const CLIP_VIZ_BSB_INFIELD_BACKHAND_HOLE_SCRIPT: AudioScript = {
  slug: "viz-bsb-infield-backhand-hole",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See a hard ground ball hit deep to your backhand side.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You read the hop and take an aggressive angle into the hole.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your first step puts you on a direct route to the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You reach across your body and field the backhand cleanly.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You gather your feet and get your shoulders toward first.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You make the long throw across the diamond on a line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The throw carries chest-high to the bag.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "It reaches the first baseman just ahead of the runner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your first step, clean backhand, and accurate throw complete the play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Baseball · Infield · diving-stop (viz play)
export const CLIP_VIZ_BSB_INFIELD_DIVING_STOP_SCRIPT: AudioScript = {
  slug: "viz-bsb-infield-diving-stop",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See a hard ground ball hit down the line to your glove side.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You read it off the bat and move across the dirt.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball stays just beyond your normal fielding range.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You dive, extend the glove, and secure the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You land with the glove closed and keep control of it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You recover to a knee, find first base, and gather your grip.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You make a firm throw across the diamond.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The first baseman stretches and secures it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You secure the ball, regain your balance, and finish the throw.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Baseball · Infield · drive-in-run (viz play)
export const CLIP_VIZ_BSB_INFIELD_DRIVE_IN_RUN_SCRIPT: AudioScript = {
  slug: "viz-bsb-infield-drive-in-run",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself in the box with a runner on third and less than two outs.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You check the infield positioning and look for a pitch you can drive through the middle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You settle into the box, shorten slightly, and stay with that approach.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The pitch is a fastball on the outer half.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stay through it and drive it the other way.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball travels on a line into right-center.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The runner scores standing up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You reach second with the ball back in the infield.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You execute the approach and drive the runner home.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Baseball · Infield · work-count-single (viz play)
export const CLIP_VIZ_BSB_INFIELD_WORK_COUNT_SINGLE_SCRIPT: AudioScript = {
  slug: "viz-bsb-infield-work-count-single",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself stay disciplined through a full-count at-bat.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The first pitch is a breaking ball just outside. Ball one.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The next fastball misses off the plate. Two balls, no strikes.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You take a strike, foul off the next pitch, and hold on a fastball below the zone.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The count is full. You stay with your strike-zone plan.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The next fastball comes into the zone.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stay short, put the barrel on it, and drive it on a line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball reaches left field for a single.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You reach first after staying within the zone for the entire at-bat.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Baseball · Infield · two-strike-battle (viz play)
export const CLIP_VIZ_BSB_INFIELD_TWO_STRIKE_BATTLE_SCRIPT: AudioScript = {
  slug: "viz-bsb-infield-two-strike-battle",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself at 0-2, making an adjustment to protect the zone.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The pitcher has room to expand beyond the plate.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You choke up, widen your stance, and shorten your move to the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He tries to expand below the zone, and you hold off. Ball one.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He spins a slider on the corner, and you foul it away.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You foul the next pitch straight back and reset.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "A fastball enters the zone, and you put a short swing on it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You send it the other way, past the shortstop.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The shorter approach lets you handle the pitch and reach first.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Baseball · Infield · next-ball-clean (viz play)
export const CLIP_VIZ_BSB_INFIELD_NEXT_BALL_CLEAN_SCRIPT: AudioScript = {
  slug: "viz-bsb-infield-next-ball-clean",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See a routine ground ball kick off your glove for an error.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The runner reaches. You have time to reset before the next pitch.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You check the outs, settle into ready position, and prepare for the next ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The next batter chops a ground ball into your range.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You move through it under control.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "With the glove out front, you field it cleanly and work through the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You set your feet and make the throw across the diamond.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The throw reaches first ahead of the runner. One out.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You finish the play, check the situation, and return to ready position.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Baseball · Outfield · run-down-gap (viz play)
export const CLIP_VIZ_BSB_OUTFIELD_RUN_DOWN_GAP_SCRIPT: AudioScript = {
  slug: "viz-bsb-outfield-run-down-gap",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See a ball driven into the gap and prepare to take the right angle.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball carries toward left-center.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You read it off the bat, take a drop step, and get moving.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You run on an angle that keeps the ball over your glove-side shoulder.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stay on the route without drifting underneath it too early.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You close the final steps and catch it in stride.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You gather after the catch and get your feet underneath you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You return the ball to the cutoff on a line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your first step and route put you under the ball in the gap.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Baseball · Outfield · throw-out-runner (viz play)
export const CLIP_VIZ_BSB_OUTFIELD_THROW_OUT_RUNNER_SCRIPT: AudioScript = {
  slug: "viz-bsb-outfield-throw-out-runner",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See a ground-ball single come through the right side with a runner on first.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The runner rounds second and considers taking third.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You charge under control and field the ball out front.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You come through the ball and line up the throw to third.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You use a crow hop and make a firm throw.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The throw travels on a line and takes one hop to the bag.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "It arrives on the fielder's glove side, ahead of the runner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The fielder applies the tag, and the umpire calls the runner out.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You keep the throw low, accurate, and ahead of the runner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Baseball · Outfield · diving-catch (viz play)
export const CLIP_VIZ_BSB_OUTFIELD_DIVING_CATCH_SCRIPT: AudioScript = {
  slug: "viz-bsb-outfield-diving-catch",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See a sinking line drive headed into shallow center.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You read the height and speed as soon as it leaves the bat.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You break forward and take a direct route.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You decide early and close the ground for a controlled dive.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You extend with the glove low to the grass.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball reaches the webbing just above the ground.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You land with the glove closed and keep control of the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The umpire signals the out.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get to your feet, return the ball to the infield, and reset your position.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Baseball · Outfield · play-the-wall (viz play)
export const CLIP_VIZ_BSB_OUTFIELD_PLAY_THE_WALL_SCRIPT: AudioScript = {
  slug: "viz-bsb-outfield-play-the-wall",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See a high drive carry toward the wall and prepare for the carom.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball is hit over your head toward the warning track.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You drop step, take your route, and continue reading the flight.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You read that the ball will hit the wall instead of clearing it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get into position, square to the wall, and prepare for the bounce.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball caroms back, and you field it cleanly on the bounce.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You turn, use a crow hop, and hit the relay on a line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The hitter sees the ball ahead of him and stops at second.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You read the wall, field the carom, and keep the hitter to a double.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Baseball · Outfield · drive-the-gap (viz play)
export const CLIP_VIZ_BSB_OUTFIELD_DRIVE_THE_GAP_SCRIPT: AudioScript = {
  slug: "viz-bsb-outfield-drive-the-gap",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself ready for a fastball you can drive into the gap.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You settle into the box and look for a fastball in the zone.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The pitcher leaves one over the plate, middle-in.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stay balanced, load on time, and take a direct path to the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The barrel meets it squarely.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball travels on a line into the left-center gap.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You leave the box hard and watch the ball as you run.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You read the gap, continue to second, and arrive ahead of the throw.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stay balanced through contact and run out the double.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Baseball · Outfield · two-strike-single (viz play)
export const CLIP_VIZ_BSB_OUTFIELD_TWO_STRIKE_SINGLE_SCRIPT: AudioScript = {
  slug: "viz-bsb-outfield-two-strike-single",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself with two strikes, shortening the swing and protecting the zone.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "At 1-2, the pitcher has room to expand.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You choke up, spread out, and shorten your move to the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He throws a fastball above the zone, and you hold off. Ball two.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He drops a breaking ball on the edge, and you foul it away.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You foul the next pitch straight back and reset.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "A fastball enters the zone, and you put the barrel on it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball travels up the middle for a single.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stay within the zone, shorten the swing, and reach first.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Baseball · Outfield · next-at-bat-clean (viz play)
export const CLIP_VIZ_BSB_OUTFIELD_NEXT_AT_BAT_CLEAN_SCRIPT: AudioScript = {
  slug: "viz-bsb-outfield-next-at-bat-clean",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself take strike three on a fastball you expected to miss the zone.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The at-bat is over. You return to the dugout and review the pitch.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Next time up, you keep the same approach but prepare earlier for that fastball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You settle into the box and track the pitch out of the hand.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The pitcher returns to the same fastball, and you recognize it sooner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stay short and put the barrel on the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball travels on a line through the left side for a single.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You run through first and look to the coach.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You take your lead from first and pick up the next sign.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const BASEBALL_VIZ_CLIP_SCRIPTS: AudioScript[] = [
  CLIP_VIZ_BSB_PITCHER_ATTACK_FIRST_INNING_SCRIPT,
  CLIP_VIZ_BSB_PITCHER_STRIKEOUT_SEQUENCE_SCRIPT,
  CLIP_VIZ_BSB_PITCHER_ESCAPE_THE_JAM_SCRIPT,
  CLIP_VIZ_BSB_PITCHER_HOLD_AND_FIELD_SCRIPT,
  CLIP_VIZ_BSB_PITCHER_PUTAWAY_PITCH_SCRIPT,
  CLIP_VIZ_BSB_PITCHER_DEEP_OUTING_RHYTHM_SCRIPT,
  CLIP_VIZ_BSB_PITCHER_BOUNCE_BACK_SCRIPT,
  CLIP_VIZ_BSB_CATCHER_FRAME_THE_ZONE_SCRIPT,
  CLIP_VIZ_BSB_CATCHER_BLOCK_IN_THE_DIRT_SCRIPT,
  CLIP_VIZ_BSB_CATCHER_THROW_OUT_THE_RUNNER_SCRIPT,
  CLIP_VIZ_BSB_CATCHER_CALL_THE_GAME_SCRIPT,
  CLIP_VIZ_BSB_CATCHER_PLAY_AT_THE_PLATE_SCRIPT,
  CLIP_VIZ_BSB_CATCHER_CLUTCH_AT_BAT_SCRIPT,
  CLIP_VIZ_BSB_CATCHER_BOUNCE_BACK_SCRIPT,
  CLIP_VIZ_BSB_INFIELD_TURN_TWO_SCRIPT,
  CLIP_VIZ_BSB_INFIELD_BACKHAND_HOLE_SCRIPT,
  CLIP_VIZ_BSB_INFIELD_DIVING_STOP_SCRIPT,
  CLIP_VIZ_BSB_INFIELD_DRIVE_IN_RUN_SCRIPT,
  CLIP_VIZ_BSB_INFIELD_WORK_COUNT_SINGLE_SCRIPT,
  CLIP_VIZ_BSB_INFIELD_TWO_STRIKE_BATTLE_SCRIPT,
  CLIP_VIZ_BSB_INFIELD_NEXT_BALL_CLEAN_SCRIPT,
  CLIP_VIZ_BSB_OUTFIELD_RUN_DOWN_GAP_SCRIPT,
  CLIP_VIZ_BSB_OUTFIELD_THROW_OUT_RUNNER_SCRIPT,
  CLIP_VIZ_BSB_OUTFIELD_DIVING_CATCH_SCRIPT,
  CLIP_VIZ_BSB_OUTFIELD_PLAY_THE_WALL_SCRIPT,
  CLIP_VIZ_BSB_OUTFIELD_DRIVE_THE_GAP_SCRIPT,
  CLIP_VIZ_BSB_OUTFIELD_TWO_STRIKE_SINGLE_SCRIPT,
  CLIP_VIZ_BSB_OUTFIELD_NEXT_AT_BAT_CLEAN_SCRIPT,
];
