// Football positive-play VIZ library (FV-423) — 49 athlete-chooseable
// rehearsal scenarios, 7 per position (QB/RB/WR/OL/DL/LB/DB). Authored by the
// content trio, verified by football-expert, KC prose-gated 2026-07-18. The
// FV-144 model: the athlete picks up to 3 of these and resolvePlaylist() plays
// them IN PLACE of the flagship viz-ftb-{role} clip (flagship = fallback).
// Registered in components/pregame/positive-plays.ts; the sport stays DORMANT
// until FV-206 wiring. Prose source of truth: docs/scripts/football.md
// ("VIZ Clips — Positive Plays") — the book wins at render time (FV-302).
//
// SAFETY: zero big-hit/injury content (clinically gated HM column only);
// zero OL body-composition content (standing guardrail).

import type { AudioScript } from "./types";
import { SCRIPT_INSTRUCTIONS, VISUALIZATION_INSTRUCTIONS } from "./instructions.ts";
import { CLIP_LOUDNORM_FILTER } from "./loudnorm.ts";

// Football · QB · rhythm-throw (viz play)
export const CLIP_VIZ_FTB_QB_RHYTHM_THROW_SCRIPT: AudioScript = {
  slug: "viz-ftb-qb-rhythm-throw",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself under center, reading the coverage before the snap.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You check the safeties \u2014 two-high, the middle open.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You already know where you're going with it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. Clean three-step drop, feet set.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your first read clears at the top of his route.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You don't wait. You trust it and let it go.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Tight spiral, right on the numbers, on time.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Caught in stride, first down.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You jog back to the huddle and get the next call.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Read it, set your feet, and deliver it on time.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · QB · play-action-shot (viz play)
export const CLIP_VIZ_FTB_QB_PLAY_ACTION_SHOT_SCRIPT: AudioScript = {
  slug: "viz-ftb-qb-play-action-shot",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the play-action shot called, and know the top is there to take.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You open with the fake and ride the mesh, hiding the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The linebackers bite downhill on the run.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You pull it and set your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your receiver has a step on the safety, down the sideline.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You drop it in over his outside shoulder.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball hangs, then falls right into his hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He runs under it in stride and finishes the play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You reset and get ready for the next snap.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · QB · rpo-read (viz play)
export const CLIP_VIZ_FTB_QB_RPO_READ_SCRIPT: AudioScript = {
  slug: "viz-ftb-qb-rpo-read",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the RPO called \u2014 hand it off, or pull and throw the bubble.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You ride the mesh with the back and read the box.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The linebacker triggers down hard to fill the run.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "That's your throw key. You pull it clean.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your eyes snap out to the bubble.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The numbers are yours \u2014 the flat is wide open.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You put it out quick and flat, on his hip.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Caught with grass ahead, first down and more.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Right read, right throw. Simple and clean.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · QB · scramble (viz play)
export const CLIP_VIZ_FTB_QB_SCRAMBLE_SCRIPT: AudioScript = {
  slug: "viz-ftb-qb-scramble",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the pocket start to break down around you.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You take your drop, but the edge caves.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You feel the rush before you see it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You climb up and slide out of the pocket, still square.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your eyes stay downfield, not on the rush.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "A receiver breaks his route off and works back to you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You reset your feet and deliver on the move.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Complete, past the sticks. First down.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You stayed composed, reset your feet, and completed the play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · QB · take-the-checkdown (viz play)
export const CLIP_VIZ_FTB_QB_TAKE_THE_CHECKDOWN_SCRIPT: AudioScript = {
  slug: "viz-ftb-qb-take-the-checkdown",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the deep shot called, but stay ready to take what they give.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. Clean drop, eyes down the field.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The coverage rolls and takes your deep man away.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Nothing's there down the field \u2014 and that's fine.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You come off it instead of forcing it into coverage.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your back leaks out of the backfield, wide open.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You drop it to him soft and let him work.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Eight easy yards. Second and short.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The safe throw kept the drive alive.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Take the available throw and keep the offense on schedule.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · QB · two-minute-drive (viz play)
export const CLIP_VIZ_FTB_QB_TWO_MINUTE_DRIVE_SCRIPT: AudioScript = {
  slug: "viz-ftb-qb-two-minute-drive",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the two-minute drive, down four, with time and field position to manage.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You break the huddle, communicate the call, and get everyone lined up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "First snap, you hit the quick out and he steps out of bounds.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The clock stops. You move them to the line fast.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Next play, you find the seam over the middle and move the ball into scoring range.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You spike it, catch your breath, and read the call.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Under a minute now, ball at the twenty.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You take the snap, climb the pocket, and put the fade where only your receiver can reach it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your receiver secures it in the end zone.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You managed the clock, made the reads, and finished the drive.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · QB · bounce-back-throw (viz play)
export const CLIP_VIZ_FTB_QB_BOUNCE_BACK_THROW_SCRIPT: AudioScript = {
  slug: "viz-ftb-qb-bounce-back-throw",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself right after a throw sails on you, incomplete.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The throw is over. You get your eyes back to the next call.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Next snap. You get back under center, eyes up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Same clean footwork, same easy read.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your first option opens on the hitch.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You trust it and drive the throw on a line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Caught, moving the chains.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The completion puts you back into the flow of the offense.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You return to the huddle ready for the next snap.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · RB · inside-zone (viz play)
export const CLIP_VIZ_FTB_RB_INSIDE_ZONE_SCRIPT: AudioScript = {
  slug: "viz-ftb-rb-inside-zone",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the inside zone called, and trust the blocks to open it.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You set your depth, eyes on the front.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. The handoff is clean \u2014 two hands, high and tight.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You press the line right at the guard's hip.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The hole shows late, the cutback lane opening.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You plant hard and cut downhill, no dancing.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "North and south now, pad level low.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You break the arm tackle at the second level.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Five more yards after contact, finished forward.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You pop up and flip the ball to the ref.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · RB · outside-zone (viz play)
export const CLIP_VIZ_FTB_RB_OUTSIDE_ZONE_SCRIPT: AudioScript = {
  slug: "viz-ftb-rb-outside-zone",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the outside zone, and read the edge before you bounce it.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You take the handoff clean, ball high and tight.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You aim for the tight end's outside hip.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You press it, stretching the front sideways.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The end sets hard \u2014 the edge is closed.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "So you plant and cut it up in the crease inside.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You slice through the seam, downhill fast.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You lower your pad level and fall forward past the safety.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You take the crease inside and move the chains.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · RB · check-release-screen (viz play)
export const CLIP_VIZ_FTB_RB_CHECK_RELEASE_SCREEN_SCRIPT: AudioScript = {
  slug: "viz-ftb-rb-check-release-screen",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the screen called your way, and sell the block first.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You slip the rusher and drift to the flat.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You turn and open your hands for the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The pass is soft, right into your chest.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your linemen are out in front, setting up their blocks.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You follow their hips and let it set up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You cut off the last block and get upfield.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Open grass now \u2014 you hit it full speed.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You follow the blocks and finish the play for a big gain.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · RB · blitz-pickup (viz play)
export const CLIP_VIZ_FTB_RB_BLITZ_PICKUP_SCRIPT: AudioScript = {
  slug: "viz-ftb-rb-blitz-pickup",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the blitz coming, and know your job is to protect.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You scan the front and read the pressure pre-snap.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Snap. The linebacker fires through the A-gap.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You step up and meet him square in the hole.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Low pad level, hands inside, feet driving.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stop his charge and hold your ground in protection.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your quarterback steps up into clean space.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball gets out downfield for a completion.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The protection holds and the quarterback completes the throw.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · RB · short-yardage (viz play)
export const CLIP_VIZ_FTB_RB_SHORT_YARDAGE_SCRIPT: AudioScript = {
  slug: "viz-ftb-rb-short-yardage",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See fourth and one, with the offense needing a yard.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Everyone in the stadium knows it's coming to you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Snap. Clean handoff, ball locked away high and tight.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You take one hard step and press the line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "No dancing \u2014 you get downhill right now.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You hit the pile low, legs churning.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You keep your feet driving through contact.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You fall forward, past the line. First down.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You get the yard and move the chains.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · RB · take-what-is-there (viz play)
export const CLIP_VIZ_FTB_RB_TAKE_WHAT_IS_THERE_SCRIPT: AudioScript = {
  slug: "viz-ftb-rb-take-what-is-there",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the run called inside, and take the yards that are there.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. Handoff clean, two hands, high and tight.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You press the hole, but it's clogged inside.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The edge looks tempting \u2014 the bounce is right there.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You don't chase it. That's how runs go backward.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stick your foot and take the tough gain up the middle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Four hard yards, downhill, pad level low.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You finish forward and fall for one more.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Second and short beats a run for a loss.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The smart yards keep the chains moving.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · RB · next-carry-clean (viz play)
export const CLIP_VIZ_FTB_RB_NEXT_CARRY_CLEAN_SCRIPT: AudioScript = {
  slug: "viz-ftb-rb-next-carry-clean",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself get stuffed at the line, no gain.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You let that carry go \u2014 it's already behind you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Next play, same call, same trust in the blocks.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. Clean handoff, ball high and tight.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You press the hole a beat longer this time.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "It opens late, and you cut downhill hard.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You burst through the second level clean.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "A big gain to answer the stuff.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "One patient carry, and you broke it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · WR · beat-the-press (viz play)
export const CLIP_VIZ_FTB_WR_BEAT_THE_PRESS_SCRIPT: AudioScript = {
  slug: "viz-ftb-wr-beat-the-press",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the corner pressed up on you, and know you'll win the release.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You set your stance, weight balanced, eyes on his hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Snap. You attack his leverage with a quick jab.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You swipe his hands off and burst past him clean.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stack him, getting on top and even.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You're a full step ahead now, running free.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball drops in over your shoulder.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You look it in and squeeze it home.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Caught clean, off the press, and gone.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · WR · slant-yac (viz play)
export const CLIP_VIZ_FTB_WR_SLANT_YAC_SCRIPT: AudioScript = {
  slug: "viz-ftb-wr-slant-yac",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the slant called and focus first on winning the route.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You take three hard steps upfield.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You break flat across the linebacker's face.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball is there quick, on your frame.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Late hands, you snatch it out of the air.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You tuck it and turn upfield in one move.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You slip the first tackle and get vertical.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get vertical and finish the run upfield.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "A quick throw turned into a big gain.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · WR · deep-ball (viz play)
export const CLIP_VIZ_FTB_WR_DEEP_BALL_SCRIPT: AudioScript = {
  slug: "viz-ftb-wr-deep-ball",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the go route called, and trust yourself to run under it.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You explode off the line, full speed.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get on top of the corner, even, then past.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You find the ball over your outside shoulder.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You track it in the air without breaking stride.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You adjust late, hands up, eyes locked on it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball drops into your hands in stride.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You look it all the way in and tuck it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You secure the catch and finish the route into the end zone.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · WR · contested-catch (viz play)
export const CLIP_VIZ_FTB_WR_CONTESTED_CATCH_SCRIPT: AudioScript = {
  slug: "viz-ftb-wr-contested-catch",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the fade called to your back shoulder, one-on-one.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You release up the sideline and create position on the corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You feel the corner draped on your hip.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball comes back-shoulder, away from him.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You throttle down and come back to it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You go up strong and high-point it at the top.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Two hands, you rip it down through the contest.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get your feet in and hang on through the ground.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You secure the catch through contact and complete the play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · WR · stalk-block (viz play)
export const CLIP_VIZ_FTB_WR_STALK_BLOCK_SCRIPT: AudioScript = {
  slug: "viz-ftb-wr-stalk-block",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the run called your way, and know your block springs it.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You release like it's a route to hold the corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He backpedals, respecting the deep ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You break down under control, feet chopping.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You fit your hands inside his chest, eyes up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You mirror him and wall him off from the play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your back cuts off your block, up the sideline.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He races past into open grass, gone.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Your block gives the back room to get up the sideline.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · WR · third-down-move-chains (viz play)
export const CLIP_VIZ_FTB_WR_THIRD_DOWN_MOVE_CHAINS_SCRIPT: AudioScript = {
  slug: "viz-ftb-wr-third-down-move-chains",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See third and long, and know the throw is coming to you.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You release clean and get vertical fast.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You read the coverage dropping off soft.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You find the marker and settle in the soft spot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You sit down just past the sticks, facing the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The pass hits you square in the numbers.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You secure it first, then turn and fall forward.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Past the line to gain. First down.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You secure the catch beyond the marker and move the chains.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · WR · run-the-next-one-clean (viz play)
export const CLIP_VIZ_FTB_WR_RUN_THE_NEXT_ONE_CLEAN_SCRIPT: AudioScript = {
  slug: "viz-ftb-wr-run-the-next-one-clean",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself drop a ball you should have had, clean off your hands.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The drop is over. You get back to the huddle and listen for the next call.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You do not protect against another drop or carry the frustration into the next route.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Next play, you line up and run it full speed.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You beat the press and stem it hard.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You snap your break, coming open again.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "This time you look it all the way in.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You show your hands late, look it in, and secure it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You complete the next catch and reset for the next play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · OL · pass-set-anchor (viz play)
export const CLIP_VIZ_FTB_OL_PASS_SET_ANCHOR_SCRIPT: AudioScript = {
  slug: "viz-ftb-ol-pass-set-anchor",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the drop-back called and focus on your pass set.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You set in your stance, hand down, eyes on the rusher.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Snap. You kick and slide, staying square.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He comes with speed, aiming for your edge.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You mirror his rush, feet quiet, hands ready.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He tries to bull you \u2014 you punch inside and anchor.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your base sinks, and he stalls against you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The pocket stays firm behind you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The pocket stays firm and the throw gets out clean.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · OL · drive-block (viz play)
export const CLIP_VIZ_FTB_OL_DRIVE_BLOCK_SCRIPT: AudioScript = {
  slug: "viz-ftb-ol-drive-block",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the run called to your gap and focus on winning your leverage.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get in your stance, eyes on your man.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You fire off low and hard, first off the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get your hat across his front.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Hands inside, you take his chest and lift.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You drive your feet in short, choppy steps.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You move him off the ball, opening the hole.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your back runs off your hip through the gap.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You sustain the block through the whistle and the back hits the gap.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · OL · reach-block (viz play)
export const CLIP_VIZ_FTB_OL_REACH_BLOCK_SCRIPT: AudioScript = {
  slug: "viz-ftb-ol-reach-block",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the zone run called, and know you'll reach the edge.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You take a quick play-side step, flat and fast.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get your head across his outside shoulder.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He tries to fight over the top to the sideline.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stay on his edge, hands inside, feet running.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You gain leverage and turn his shoulders.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You seal him inside, away from the play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The back bends it right off your block.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Edge sealed. He hits the crease clean.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · OL · pull-and-kick (viz play)
export const CLIP_VIZ_FTB_OL_PULL_AND_KICK_SCRIPT: AudioScript = {
  slug: "viz-ftb-ol-pull-and-kick",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the trap called, and picture yourself leading the play.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You pull flat down the line, quick and low.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You keep your eyes in the hole for your man.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The end crashes down, right into your path.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You square up and strike him with your inside hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You kick him out, sealing the wall.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The crease opens up right behind you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your back shoots through it downhill.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Your kick-out opens the crease and the back gets downhill.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · OL · pass-off-the-stunt (viz play)
export const CLIP_VIZ_FTB_OL_PASS_OFF_THE_STUNT_SCRIPT: AudioScript = {
  slug: "viz-ftb-ol-pass-off-the-stunt",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the twist coming, and trust your rules to pass it off.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You set to your man and stay square.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The end crashes inside, the tackle looping behind.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You feel the pick and don't chase it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You pass the crasher to your guard, eyes outside.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You slide to pick up the looper coming free.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You punch him inside and ride him wide.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "No free rusher gets through. The pocket holds.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You and the guard sort the stunt and keep the pocket clean.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · OL · combo-climb (viz play)
export const CLIP_VIZ_FTB_OL_COMBO_CLIMB_SCRIPT: AudioScript = {
  slug: "viz-ftb-ol-combo-climb",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the double-team called, and know you'll climb to the backer.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You and your guard hit the down lineman together.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Four hands, one man \u2014 you jolt him off the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You feel your guard take over the block.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You come off late, eyes up to the second level.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The linebacker fills downhill toward the gap.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You climb clean and fit your hands on him.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You wall him off and run your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Both defenders blocked. The back cuts through.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · OL · win-the-next-rep (viz play)
export const CLIP_VIZ_FTB_OL_WIN_THE_NEXT_REP_SCRIPT: AudioScript = {
  slug: "viz-ftb-ol-win-the-next-rep",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself get beat on a rep, your man winning clean.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "That snap is over. You reset your stance and your eyes.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You do not over-set or change your technique trying to make up for it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Next play, you get back in your stance, eyes calm.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You set quick, hands loaded, base under you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He tries the same speed rush again.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "This time you punch first and lock him out.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You anchor, mirror, and ride him past the pocket.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You keep the pocket clean on the next rep.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Football · DL · get-off (viz play)
export const CLIP_VIZ_FTB_DL_GET_OFF_SCRIPT: AudioScript = {
  slug: "viz-ftb-dl-get-off",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself across the ball, coiled and ready to win the get-off.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You key the football, weight loaded, eyes on the tip of the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Snap. You fire off first, low and hard, beating the guard to the spot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your hands land inside his chest before he can set.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You lock him out, hold your gap, and feel the run develop.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The back cuts toward your gap. You shed the block clean.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You come off square, eyes on the ball carrier.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You break down, wrap him up, and drive your feet through the tackle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Stopped for no gain. You peel off and get back to the huddle, ready for the next one.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · DL · stack-shed (viz play)
export const CLIP_VIZ_FTB_DL_STACK_SHED_SCRIPT: AudioScript = {
  slug: "viz-ftb-dl-stack-shed",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself head-up on the lineman, ready to take him on and read it.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. He fires out at you, hat down, trying to move you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You strike first \u2014 hands inside, pad under pad, and you anchor.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stack him up and hold your ground at the line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You keep your eyes in the backfield, reading the back through the block.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He commits to your side. You shed hard toward the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You come off the block clean, square to the ball carrier.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You fill the lane, wrap up, and finish the tackle for no gain.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The pile stops at the line. You come off it and get set for the next snap.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · DL · win-the-edge (viz play)
export const CLIP_VIZ_FTB_DL_WIN_THE_EDGE_SCRIPT: AudioScript = {
  slug: "viz-ftb-dl-win-the-edge",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself on the edge, third and long, ready to rush the passer.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You know it's a pass. You get off on the ball, first step upfield.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You attack half the man, aiming for his outside shoulder.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He kicks to set, but your get-off already has him beat.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You dip your shoulder, bend the edge, and turn the corner tight.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "His hands miss as you rip through and flatten to the quarterback.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You close the space fast \u2014 he's still looking downfield.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get home clean, wrap him up, and bring him down.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Sack. You pop up and get back to the huddle for the next rush.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · DL · hands-up (viz play)
export const CLIP_VIZ_FTB_DL_HANDS_UP_SCRIPT: AudioScript = {
  slug: "viz-ftb-dl-hands-up",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself rushing the passer, working to win your lane.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You get off and press the tackle, working your hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He mirrors you and stays square \u2014 no clean lane home.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You feel the quarterback set to throw, still just out of reach.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stop trying to run through and get your eyes on the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You throw your hands straight up into the passing lane.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The throw comes \u2014 and you get a piece of it at the line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball flutters and falls incomplete, batted down.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The ball falls incomplete and the defense gets off the field.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · DL · goal-line (viz play)
export const CLIP_VIZ_FTB_DL_GOAL_LINE_SCRIPT: AudioScript = {
  slug: "viz-ftb-dl-goal-line",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself on the goal line, with the offense trying to run through your gap.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "They're going to run it right at you. You get low in your stance.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Snap. The line fires out to move you off the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You strike first, hands inside, and drop your base.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You drop your base, hold your ground, and keep the gap closed.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The back dives for the line, looking for a crease.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "There's no crease. You've clogged it up with the whole front.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You come off the block and meet him in the hole, head up and low.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Stopped short. Goal-line stand. The defense holds.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · DL · contain-scramble (viz play)
export const CLIP_VIZ_FTB_DL_CONTAIN_SCRAMBLE_SCRIPT: AudioScript = {
  slug: "viz-ftb-dl-contain-scramble",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself rushing, disciplined, staying in your rush lane.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You get off and press your rush up the field.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The pocket starts to break down and the quarterback feels it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He steps up, looking to escape and make a play with his legs.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You don't chase the sack out of your lane \u2014 you stay home.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You keep your rush lane, squeeze him back inside, no escape.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He's got nowhere to run. You close from your edge.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You corral him and wrap him up before he crosses the line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You keep contain and stop the scramble before the line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · DL · pursue-backside (viz play)
export const CLIP_VIZ_FTB_DL_PURSUE_BACKSIDE_SCRIPT: AudioScript = {
  slug: "viz-ftb-dl-pursue-backside",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself on the backside of a run, ready to chase it flat down the line.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. The tackle reaches you and seals you from your gap.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "For a beat, you're hooked and the run is going away from you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You rip off the block and get back into pursuit.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You run flat down the line of scrimmage and stay in the play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The back cuts back, looking for the backside crease.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You close the backside crease as the back cuts toward it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You run him down from behind and drag him to the turf.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You recover from the block and make the tackle on the cutback.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · LB · read-and-fill (viz play)
export const CLIP_VIZ_FTB_LB_READ_AND_FILL_SCRIPT: AudioScript = {
  slug: "viz-ftb-lb-read-and-fill",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself in the box, eyes on your keys, ready for the snap.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You read the guard and the backfield, patient at the snap.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The guard down-blocks and the back presses the hole \u2014 it's a run.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You trigger downhill, no hesitation, filling your gap.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "A lineman climbs to block you. You take him on with your hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You keep your shoulders square and stay clean off the block.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You shed, find the back, and close the space fast.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Head up, you wrap him up and drive your feet through the tackle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Stopped for a short gain. You pop up and signal the next call.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · LB · take-on-lead (viz play)
export const CLIP_VIZ_FTB_LB_TAKE_ON_LEAD_SCRIPT: AudioScript = {
  slug: "viz-ftb-lb-take-on-lead",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself reading a power play developing right at you.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You see the guard pull and the lead blocker climbing to you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You trigger downhill and meet the block in the hole, not on your heels.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You strike the blocker with your hands, pad under pad.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You keep your outside arm free and hold your leverage.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You force the run back inside, to your help.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The back has to cut it up into the traffic.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your help is there, and you come off to finish the tackle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Short gain, run defended. You reset the front and get the call in.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · LB · zone-drop (viz play)
export const CLIP_VIZ_FTB_LB_ZONE_DROP_SCRIPT: AudioScript = {
  slug: "viz-ftb-lb-zone-drop",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself dropping into your zone, eyes up on the quarterback.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You read pass and open into your drop, feeling the routes.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "A receiver crosses into your zone \u2014 you carry him with your eyes.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You settle in the window and keep your eyes on the quarterback.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He winds up to throw over the middle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You read his eyes and break the instant the ball leaves his hand.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You drive downhill on the throw, closing the window.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You arrive as the ball does and knock it away clean.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Incomplete. Third down stop. You made them punt.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · LB · cover-the-back (viz play)
export const CLIP_VIZ_FTB_LB_COVER_THE_BACK_SCRIPT: AudioScript = {
  slug: "viz-ftb-lb-cover-the-back",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself matched on the back, ready to run with him in coverage.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. He slips out of the backfield on a route to the flat.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You don't bite on the play fake \u2014 you stay locked on the back.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You open your hips and run with him step for step.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He tries to break it upfield on a wheel.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stay on top and keep your leverage, no separation.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The quarterback looks, but there's no window to throw.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He comes off it, and the back is covered all the way.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The quarterback comes off the route because you stay in coverage.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · LB · blitz (viz play)
export const CLIP_VIZ_FTB_LB_BLITZ_SCRIPT: AudioScript = {
  slug: "viz-ftb-lb-blitz",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself walked up, timing the snap, ready to bring the blitz.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get the call and creep toward your gap late.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Snap. You time it clean and shoot the A-gap downhill.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You're through the line before the guard can pick you up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You bend flat to the quarterback, eyes on the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He never sees you coming downhill through the pocket.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You close the last step and wrap him up clean.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You bring him down before he can get the throw off.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Sack. You pop up and get the defense lined up again.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · LB · goal-line (viz play)
export const CLIP_VIZ_FTB_LB_GOAL_LINE_SCRIPT: AudioScript = {
  slug: "viz-ftb-lb-goal-line",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself stacked in the box on the goal line, ready to fill your gap.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "They're going to try to pound it in. You get downhill in your stance.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Snap. You read run and trigger fast, no false steps.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You beat the blocker to the hole and fill it downhill.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You meet the back in the gap before he reaches the line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Head up, you get your pads under his and stand him up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You wrap, squeeze, and drive your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He doesn't get across. Your help swarms to finish it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Goal-line stand. The defense holds and takes over the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · LB · recover-play-action (viz play)
export const CLIP_VIZ_FTB_LB_RECOVER_PLAY_ACTION_SCRIPT: AudioScript = {
  slug: "viz-ftb-lb-recover-play-action",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself reading run, then catching yourself on the play fake.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. The line shows run and you take a step downhill.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "It's play-action \u2014 the back doesn't have it, the quarterback pulls it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "For a beat, you're out of your drop and a step out of position.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You don't panic or grab \u2014 you get your eyes back to your keys.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You flip and drop back into your zone, recovering fast.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You find the crosser and read the quarterback's eyes.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He throws, and you break on it, driving through the window.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You recover into the window and knock the pass away.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · DB · press-man (viz play)
export const CLIP_VIZ_FTB_DB_PRESS_MAN_SCRIPT: AudioScript = {
  slug: "viz-ftb-db-press-man",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself pressed over your man, eyes on his hips and feet balanced.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. He releases, and you don't lunge \u2014 patient feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You mirror his first move and get your hands on him at the line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stay hip to hip, running with him stride for stride.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He can't stack you \u2014 you're in phase the whole way.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He breaks, and you drive on it, closing the cushion.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball comes on his break, in front of you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You drive through his hands and knock it away clean.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Incomplete. You reset and get ready for the next coverage call.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · DB · off-break (viz play)
export const CLIP_VIZ_FTB_DB_OFF_BREAK_SCRIPT: AudioScript = {
  slug: "viz-ftb-db-off-break",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself in off coverage, reading the route through his stem.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You backpedal, patient, keeping your cushion.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You read his stem and feel the route developing underneath.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He sits down in the hook, and the quarterback loads to throw.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You plant off your cushion and break downhill on the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You close the ground fast, driving on the catch point.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You arrive as the ball does, right on his hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You arrive through the hands and break the pass up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Incomplete. You read the route and close the window.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · DB · pick (viz play)
export const CLIP_VIZ_FTB_DB_PICK_SCRIPT: AudioScript = {
  slug: "viz-ftb-db-pick",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself reading the concept and holding your leverage long enough to invite the throw.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You get depth and keep your eyes on the quarterback.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You read the route combination and see the throw before it comes.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You recognize the throw and drive in front of the receiver.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball's in the air, and you're already breaking to it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You attack it at the high point with both hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You pick it clean and tuck it away.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get your feet under you and turn upfield with the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You secure the interception and get the offense the ball back.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · DB · run-support (viz play)
export const CLIP_VIZ_FTB_DB_RUN_SUPPORT_SCRIPT: AudioScript = {
  slug: "viz-ftb-db-run-support",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself reading run, coming downhill as the force in the alley.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. You read run and trigger, driving toward the line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The back breaks outside, looking for room in the alley.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You fill fast but under control, breaking down as you close.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You keep leverage, forcing him back inside to your help.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You square him up, head up, in a good tackling position.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You wrap him up and drive your feet on contact.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You bring him down in space, a sure open-field tackle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Short gain. You reset and get the next coverage call.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · DB · set-the-edge (viz play)
export const CLIP_VIZ_FTB_DB_SET_THE_EDGE_SCRIPT: AudioScript = {
  slug: "viz-ftb-db-set-the-edge",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself as the force player on the edge of a perimeter run.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. The run breaks your way and the receiver comes to block you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You trigger down and meet him before he gets into your chest.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You strike him with your hands and keep your outside arm free.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You hold the edge \u2014 you don't get turned or reached.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You force the ball back inside, to your help.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The back has to cut up into the traffic.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You shed the block and come off to help finish the tackle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You keep the edge set and force the run back to your help.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · DB · clutch-deep (viz play)
export const CLIP_VIZ_FTB_DB_CLUTCH_DEEP_SCRIPT: AudioScript = {
  slug: "viz-ftb-db-clutch-deep",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself matched on their best receiver late in the game, with no help over the top.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. He releases hard, trying to get on top of you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stay patient, in phase, eyes on his hips, not the noise.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He goes vertical, and you run with him stride for stride.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball goes up deep toward your side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stay on top, get your eyes back, and find the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stay in phase, find the ball, and play through his hands at the catch point.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You knock it away clean as it comes down.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Incomplete. You finish the rep and reset for the next snap.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Football · DB · recover-in-phase (viz play)
export const CLIP_VIZ_FTB_DB_RECOVER_IN_PHASE_SCRIPT: AudioScript = {
  slug: "viz-ftb-db-recover-in-phase",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself on your man, then feeling him get a step on your break.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Snap. He releases and stems you, and you open your hips too early.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "For a beat, he's got half a step and you're trailing.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You do not grab or look back too early. You keep running to recover.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You dig, get back to his hip, and recover into phase.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You close the cushion, running stride for stride again.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball's in the air, a step ahead of you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get your eyes back, find it, and rake it away at the catch point.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Incomplete. You recover your position and finish through the catch point.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

export const FOOTBALL_VIZ_CLIP_SCRIPTS: readonly AudioScript[] = [
  CLIP_VIZ_FTB_QB_RHYTHM_THROW_SCRIPT,
  CLIP_VIZ_FTB_QB_PLAY_ACTION_SHOT_SCRIPT,
  CLIP_VIZ_FTB_QB_RPO_READ_SCRIPT,
  CLIP_VIZ_FTB_QB_SCRAMBLE_SCRIPT,
  CLIP_VIZ_FTB_QB_TAKE_THE_CHECKDOWN_SCRIPT,
  CLIP_VIZ_FTB_QB_TWO_MINUTE_DRIVE_SCRIPT,
  CLIP_VIZ_FTB_QB_BOUNCE_BACK_THROW_SCRIPT,
  CLIP_VIZ_FTB_RB_INSIDE_ZONE_SCRIPT,
  CLIP_VIZ_FTB_RB_OUTSIDE_ZONE_SCRIPT,
  CLIP_VIZ_FTB_RB_CHECK_RELEASE_SCREEN_SCRIPT,
  CLIP_VIZ_FTB_RB_BLITZ_PICKUP_SCRIPT,
  CLIP_VIZ_FTB_RB_SHORT_YARDAGE_SCRIPT,
  CLIP_VIZ_FTB_RB_TAKE_WHAT_IS_THERE_SCRIPT,
  CLIP_VIZ_FTB_RB_NEXT_CARRY_CLEAN_SCRIPT,
  CLIP_VIZ_FTB_WR_BEAT_THE_PRESS_SCRIPT,
  CLIP_VIZ_FTB_WR_SLANT_YAC_SCRIPT,
  CLIP_VIZ_FTB_WR_DEEP_BALL_SCRIPT,
  CLIP_VIZ_FTB_WR_CONTESTED_CATCH_SCRIPT,
  CLIP_VIZ_FTB_WR_STALK_BLOCK_SCRIPT,
  CLIP_VIZ_FTB_WR_THIRD_DOWN_MOVE_CHAINS_SCRIPT,
  CLIP_VIZ_FTB_WR_RUN_THE_NEXT_ONE_CLEAN_SCRIPT,
  CLIP_VIZ_FTB_OL_PASS_SET_ANCHOR_SCRIPT,
  CLIP_VIZ_FTB_OL_DRIVE_BLOCK_SCRIPT,
  CLIP_VIZ_FTB_OL_REACH_BLOCK_SCRIPT,
  CLIP_VIZ_FTB_OL_PULL_AND_KICK_SCRIPT,
  CLIP_VIZ_FTB_OL_PASS_OFF_THE_STUNT_SCRIPT,
  CLIP_VIZ_FTB_OL_COMBO_CLIMB_SCRIPT,
  CLIP_VIZ_FTB_OL_WIN_THE_NEXT_REP_SCRIPT,
  CLIP_VIZ_FTB_DL_GET_OFF_SCRIPT,
  CLIP_VIZ_FTB_DL_STACK_SHED_SCRIPT,
  CLIP_VIZ_FTB_DL_WIN_THE_EDGE_SCRIPT,
  CLIP_VIZ_FTB_DL_HANDS_UP_SCRIPT,
  CLIP_VIZ_FTB_DL_GOAL_LINE_SCRIPT,
  CLIP_VIZ_FTB_DL_CONTAIN_SCRAMBLE_SCRIPT,
  CLIP_VIZ_FTB_DL_PURSUE_BACKSIDE_SCRIPT,
  CLIP_VIZ_FTB_LB_READ_AND_FILL_SCRIPT,
  CLIP_VIZ_FTB_LB_TAKE_ON_LEAD_SCRIPT,
  CLIP_VIZ_FTB_LB_ZONE_DROP_SCRIPT,
  CLIP_VIZ_FTB_LB_COVER_THE_BACK_SCRIPT,
  CLIP_VIZ_FTB_LB_BLITZ_SCRIPT,
  CLIP_VIZ_FTB_LB_GOAL_LINE_SCRIPT,
  CLIP_VIZ_FTB_LB_RECOVER_PLAY_ACTION_SCRIPT,
  CLIP_VIZ_FTB_DB_PRESS_MAN_SCRIPT,
  CLIP_VIZ_FTB_DB_OFF_BREAK_SCRIPT,
  CLIP_VIZ_FTB_DB_PICK_SCRIPT,
  CLIP_VIZ_FTB_DB_RUN_SUPPORT_SCRIPT,
  CLIP_VIZ_FTB_DB_SET_THE_EDGE_SCRIPT,
  CLIP_VIZ_FTB_DB_CLUTCH_DEEP_SCRIPT,
  CLIP_VIZ_FTB_DB_RECOVER_IN_PHASE_SCRIPT,
];
