// Lacrosse positive-play VIZ library (FV-406) — 40 athlete-facing
// visualization clips: 5 position flagships (attack/midfield/defense/fogo/
// goalie) + 35 athlete-chooseable rehearsal scenarios, 7 per position.
// Authored by the content trio, verified by lacrosse-expert, KC prose-gated.
// The FV-144 model: the athlete picks up to 3 plays and resolvePlaylist() plays
// them IN PLACE of the flagship viz-lax-{position} clip (flagship = nothing-
// picked fallback). Registered in components/pregame/positive-plays.ts; the
// sport stays DORMANT (not in SUPPORTED_SPORTS) until the FV-407 go-live gate.
// Prose source of truth: docs/scripts/lacrosse.md ("VIZ Clips — Flagships" +
// "VIZ Clips — Positive Plays") — the book wins at render time (FV-302).

import type { AudioScript } from "./types";
import { SCRIPT_INSTRUCTIONS, VISUALIZATION_INSTRUCTIONS } from "./instructions.ts";
import { CLIP_LOUDNORM_FILTER } from "./loudnorm.ts";

// ── Lacrosse VIZ clips — position flagships (FV-406) ────────────────────────

// Lacrosse · Attack · VIZ (flagship)
export const CLIP_VIZ_LAX_ATTACK_SCRIPT: AudioScript = {
  slug: "viz-lax-attack",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "Keep your eyes closed. See yourself walking onto the field.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 1 },
    { type: "speech", text: "You hear the ball snapping into pockets in warmups.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 1 },
    { type: "speech", text: "Hear cleats on the turf, a coach calling out the lines.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You feel the field under your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.2 },
    { type: "speech", text: "Feel your gloves close around the shaft.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.2 },
    { type: "speech", text: "Feel your helmet settle, the chin strap snug.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You settle your breathing and prepare for the first possession.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 1.25 },
    { type: "speech", text: "You set up at X with the ball and identify where the first slide will come from.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 0.25 },
    { type: "speech", text: "You split dodge from X, gain a step, and roll back when the defender overplays.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You turn the corner at GLE, free your hands, and finish low to high at the far pipe.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The shot reaches the net, and you return to your spot for the next call.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Next possession, you slip the pick in the two-man game and catch on the move.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You keep the stick protected through contact and finish inside the far pipe.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "See the next possession develop from up top.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You use a question-mark dodge to gain separation, and when the double commits, you feed the crease on time.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "When the slide arrives early and closes the lane, you pull the ball out and move it to the open side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Now visualize the next play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 0.8 },
    { type: "speech", text: "On the next look, you work away from the shut-off, catch on the move, and release the shot before the slide arrives.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Lacrosse · Midfield · VIZ (flagship)
export const CLIP_VIZ_LAX_MIDFIELD_SCRIPT: AudioScript = {
  slug: "viz-lax-midfield",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "Keep your eyes closed. See yourself walking onto the field.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 1 },
    { type: "speech", text: "You hear the ball snapping into pockets in warmups.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 1 },
    { type: "speech", text: "Hear cleats on the turf, a coach calling out the lines.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You feel the field under your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.2 },
    { type: "speech", text: "Feel your gloves close around the shaft.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.2 },
    { type: "speech", text: "Feel your helmet settle, the chin strap snug.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You settle your breathing and prepare for the first shift.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 1.25 },
    { type: "speech", text: "You cross midfield on the run and scan the numbers ahead.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 0.25 },
    { type: "speech", text: "A ground ball comes loose at midfield. You get low, scoop through it with two hands, and move it forward.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You carry into space, draw the pole, and keep your head up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You hit the trailer in stride, fill the next lane, and the offense finishes the break.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Next shift, you split the short-stick from up top, get downhill, and shoot far pipe on the run.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You recover through midfield and pick up the next assignment.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "See the next defensive possession turn into transition.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You ride the ball carrier, disrupt the outlet, scoop the ground ball, and move it to the open wing.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "When the numbers disappear, you pull the ball out and let the offense get organized.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Now visualize the next play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 0.8 },
    { type: "speech", text: "You trail the next break, catch the swing pass, and step into a time-and-room shot to the far side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Lacrosse · Defense · VIZ (flagship)
export const CLIP_VIZ_LAX_DEFENSE_SCRIPT: AudioScript = {
  slug: "viz-lax-defense",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "Keep your eyes closed. See yourself walking onto the field.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 1 },
    { type: "speech", text: "You hear the ball snapping into pockets in warmups.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 1 },
    { type: "speech", text: "Hear cleats on the turf, a coach calling out the lines.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You feel the field under your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.2 },
    { type: "speech", text: "Feel your gloves close around the long pole.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.2 },
    { type: "speech", text: "Feel your helmet settle, the chin strap snug.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You settle your breathing and prepare for the first matchup.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 1.25 },
    { type: "speech", text: "You pick up the attackman at X, keep the pole in front, and confirm where your help is.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 0.25 },
    { type: "speech", text: "He drives topside. You move your feet, stay on his hands, and force him behind the cage.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He tries again. You break down and place one controlled poke on his bottom hand.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You take away his strong hand, and he moves the ball back up top.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "On the next dodge, you arrive with the slide, close his hands, and force a low-angle shot the goalie handles.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The defense collects the ball and starts the clear.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "See yourself communicate through the next possession.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You approach under control, steer him to his weak hand, call the slide, then scoop the loose ball and hit the outlet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "When he gains a step, you recover to his hands and trust the slide instead of reaching for a desperate check.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Now visualize the next play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 0.8 },
    { type: "speech", text: "On a late possession, you keep your leverage, force the dodger to his weak hand, and make him move the ball away from the cage.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Lacrosse · FOGO · VIZ (flagship)
export const CLIP_VIZ_LAX_FOGO_SCRIPT: AudioScript = {
  slug: "viz-lax-fogo",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "Keep your eyes closed. See yourself walking onto the field.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 1 },
    { type: "speech", text: "You hear the ball snapping into pockets in warmups.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 1 },
    { type: "speech", text: "Hear cleats on the turf, a coach calling out the lines.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You feel the field under your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.2 },
    { type: "speech", text: "Feel your gloves close around the shaft.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.2 },
    { type: "speech", text: "Feel your helmet settle, the chin strap snug.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You settle your breathing and check your grip and stance.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 1.25 },
    { type: "speech", text: "You walk to the X, set your feet at the dot, and prepare for one draw.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 0.25 },
    { type: "speech", text: "Down, set. On the whistle, your clamp gets to the ball first.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You control the ball and rake it toward your wing.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your wing scoops through it and moves the ball to the offense.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "On the next draw, he counters quickly. You go over the top, stop his exit, and pull the ball to space.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You scoop, protect the stick, and make the outlet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "See another draw stall under both sticks.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stay low, keep pressure on his hands, and direct the loose ball toward your wing.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "When he wins the clamp, you stop the exit, keep the ball contested, and let the wing matchup decide possession.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Now visualize the next play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 0.8 },
    { type: "speech", text: "On a late draw, you clamp, direct the ball to space, scoop it, and make the short outlet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Lacrosse · Goalie · VIZ (flagship)
export const CLIP_VIZ_LAX_GOALIE_SCRIPT: AudioScript = {
  slug: "viz-lax-goalie",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "Keep your eyes closed. See yourself walking onto the field.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 1 },
    { type: "speech", text: "You hear the ball snapping into pockets in warmups.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 1 },
    { type: "speech", text: "Hear cleats on the turf, a coach calling out the lines.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You feel the crease under your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.2 },
    { type: "speech", text: "Feel your gloves close around the shaft.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.2 },
    { type: "speech", text: "Feel your chest protector settle, the helmet snug.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You settle your breathing and set your stance.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 1.25 },
    { type: "speech", text: "You step into the cage, call the hot defender and the second slide, and set your angle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 0.25 },
    { type: "speech", text: "A shooter winds up from twelve yards, and you track the release off the stick.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You step toward the shot, drive both hands stick-side high, and control it in the pocket.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You look upfield and hit the breaking midfielder on the wing.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The outlet starts transition before the ride can organize.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "On the next shot, you stay square, get the stick to the low bounce first, and control the rebound.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "See the next possession develop from behind the defense.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You set the angle early, stay square, drive both hands to the step-down shot, and direct the rebound to the corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "When one gets by you, you reset your feet, make the defensive calls, and prepare for the next shot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Now visualize the next play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 0.8 },
    { type: "speech", text: "On a man-down feed to the crease, you hold the angle, step to the shot, and steer the rebound to the pole in the corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// ── Lacrosse VIZ clips — positive-play library, 7 per position (FV-406) ─────

// Lacrosse · Attack · beat-your-man (viz play)
export const CLIP_VIZ_LAX_ATTACK_BEAT_YOUR_MAN_SCRIPT: AudioScript = {
  slug: "viz-lax-attack-beat-your-man",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself at X with the ball, reading your matchup and the first slide.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You split dodge, gain a step, and roll back when the defender overplays.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You turn the corner at GLE, free your hands, and finish low to high at the far pipe.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The shot reaches the net, and you return to X for the next possession.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Next possession, you slip the pick in the two-man game and catch on the move.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You protect the stick through contact and release the shot before the recovery arrives.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "When the slide comes early and closes the lane, you keep the stick protected.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You pull the ball out and move it to the open side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On the next possession, the defender denies you at X.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You cut away from the shut-off, catch on the move, and release before the slide arrives.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Attack · see-the-field (viz play)
export const CLIP_VIZ_LAX_ATTACK_SEE_THE_FIELD_SCRIPT: AudioScript = {
  slug: "viz-lax-attack-see-the-field",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself at X, scanning the crease and the adjacent slide.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You drive from X and see the crease defender begin to slide.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You carry the slide far enough, then deliver the feed to the crease.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your teammate catches and finishes before the defense can recover.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Next trip, you send the skip pass to the weak-side shooter's outside shoulder.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On the man-up, you move it one more until the open player has the catch-and-shoot look.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "When the defense takes away the inside feed, you keep possession.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You pull the ball out and restart the set.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On the clear, you take an angle that steers the ball carrier toward the sideline.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The pass goes to the sideline, where you intercept it and move it to the open teammate.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Attack · finish-on-crease (viz play)
export const CLIP_VIZ_LAX_ATTACK_FINISH_ON_CREASE_SCRIPT: AudioScript = {
  slug: "viz-lax-attack-finish-on-crease",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself on the crease, sealing the defender and showing a target.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball is up top, and your teammate begins the dodge.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your defender leaves to slide.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You keep position, turn your shoulders, and open the stick to the feed.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The feed arrives low and firm.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You receive it with soft hands and keep the head of the stick protected.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You release it in one motion without winding up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The quick stick travels low to high inside the far pipe.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You catch and release before the defender can recover to the crease.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Attack · time-and-room (viz play)
export const CLIP_VIZ_LAX_ATTACK_TIME_AND_ROOM_SCRIPT: AudioScript = {
  slug: "viz-lax-attack-time-and-room",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself up top with the ball and space in front of you.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The defense stays below you and leaves room for the shot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You set your feet and bring your hands away from your body.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You load on the back foot and step toward the target.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your hips and shoulders move through the shot together.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You finish over the front foot with an overhand release.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball travels off-stick high.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The shot reaches the corner before the goalie can set to it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You used the available space and completed the shooting motion on balance.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Attack · ride-force-turnover (viz play)
export const CLIP_VIZ_LAX_ATTACK_RIDE_FORCE_TURNOVER_SCRIPT: AudioScript = {
  slug: "viz-lax-attack-ride-force-turnover",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself as the first rider, taking away the middle of the field.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The goalie makes the save and looks for the first outlet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You approach on an angle that sends the ball carrier toward the sideline.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He turns his shoulders and looks for the next pass.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You close on his hands and delay the release.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Under pressure, he sends the pass up the sideline.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You read the pass and catch it cleanly out of the air.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You protect the stick and look inside from thirty yards out.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You move it to the open teammate before the defense finishes matching up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Lacrosse · Attack · man-up-finish (viz play)
export const CLIP_VIZ_LAX_ATTACK_MAN_UP_FINISH_SCRIPT: AudioScript = {
  slug: "viz-lax-attack-man-up-finish",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself on the man-up, set on the wing as the ball moves around the perimeter.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The unit keeps the passes firm and moves the defense with each catch.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The rotation leaves your side open for a moment.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball swings to you as the defender begins to close out.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You catch with your hands ready and step toward the cage.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You have room to release before the rotation reaches you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You shoot overhand before the defender closes the space.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The shot stays low and reaches the far pipe.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You complete the catch-and-shoot look created by the ball movement.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Attack · next-look-clean (viz play)
export const CLIP_VIZ_LAX_ATTACK_NEXT_LOOK_CLEAN_SCRIPT: AudioScript = {
  slug: "viz-lax-attack-next-look-clean",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself get open on the crease for a close-range feed.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The feed reaches your stick, and you release before controlling it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The shot misses high.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball goes out of bounds, and you turn and ride.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On a later possession, you seal the defender and show your stick again.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The feed returns to the same area.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You receive it first, keep the hands soft, and make a compact release.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The quick stick stays low and inside the pipe.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You run through the crease and pick up the next assignment.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Midfield · push-the-ball (viz play)
export const CLIP_VIZ_LAX_MIDFIELD_PUSH_THE_BALL_SCRIPT: AudioScript = {
  slug: "viz-lax-midfield-push-the-ball",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself crossing midfield with the ball and scanning the numbers ahead.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "A ground ball comes loose at midfield. You get low and scoop through it with two hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You carry into space, draw the pole, and keep your head up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You hit the trailer in stride and fill the next lane.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Next shift, you split the short-stick from up top and get downhill.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You keep the stick protected, draw the next defender, and move the ball to the open side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "When the defense matches up and the break is gone, you keep possession.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You pull the ball out and let the offense get organized.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On the next transition, you trail the play and catch the swing pass.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You set your feet and take the time-and-room shot to the far side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Midfield · cover-both-ends (viz play)
export const CLIP_VIZ_LAX_MIDFIELD_COVER_BOTH_ENDS_SCRIPT: AudioScript = {
  slug: "viz-lax-midfield-cover-both-ends",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the ball turn over and pick up the nearest midfielder at the midline.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The midfielder dodges, and you close the lane without overcommitting.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The pass hits the turf. You call man-ball, scoop through it, and protect the stick.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You move it to the first outlet and start transition.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On a long defensive possession, you stay connected to the matchup and keep the middle closed.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On the faceoff wing, you box out, track the loose ball, and help secure possession.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Late in the shift, you take the direct route through the middle on the backcheck.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You force the ball wide, communicate the matchup, then sub through the box.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On the next fast break, you again recover through the middle and identify the most dangerous player.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The offense is pushed to a low-angle shot that the goalie can track.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Midfield · shoot-on-the-run (viz play)
export const CLIP_VIZ_LAX_MIDFIELD_SHOOT_ON_THE_RUN_SCRIPT: AudioScript = {
  slug: "viz-lax-midfield-shoot-on-the-run",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself filling the lane as the ball swings your way.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You catch on the move with the stick protected to the outside.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You keep running and bring your hands away from your body.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You load through the hips without shortening your stride.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your shoulders and hips turn through the release.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You release the shot without breaking stride.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The ball travels overhand toward the far side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The shot reaches the open space before the goalie finishes moving across.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You complete the shooting motion on balance and continue through the play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Midfield · both-ends-shift (viz play)
export const CLIP_VIZ_LAX_MIDFIELD_BOTH_ENDS_SHIFT_SCRIPT: AudioScript = {
  slug: "viz-lax-midfield-both-ends-shift",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself pick up your man as the ball turns over.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Their midfielder drives, and you arrive with the first slide.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You close his hands and force the pass away from the crease.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The pass hits the turf, and you scoop through it with two hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You protect the stick and carry into the open side of the field.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You cross midfield and identify the advantage.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You draw the final defender and pass to the trailer.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The trailer catches in stride and finishes the transition chance.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You recover through the middle and prepare for the next substitution.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Midfield · ground-ball-scrum (viz play)
export const CLIP_VIZ_LAX_MIDFIELD_GROUND_BALL_SCRUM_SCRIPT: AudioScript = {
  slug: "viz-lax-midfield-ground-ball-scrum",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See a loose ball between several players and approach under control.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You call man-ball and identify the opponent nearest the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get your hips low and box the opponent away from the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You keep both hands on the stick and scoop through the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Contact arrives as you bring the stick tight to your body.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You move out of traffic and protect the head of the stick.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get your head up and find the open outlet on the wing.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You deliver the pass to the outside shoulder.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The outlet receives it and carries the ball into the offensive half.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Midfield · slide-and-rotate (viz play)
export const CLIP_VIZ_LAX_MIDFIELD_SLIDE_AND_ROTATE_SCRIPT: AudioScript = {
  slug: "viz-lax-midfield-slide-and-rotate",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself off-ball, set as the first slide.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Their midfielder gains a step and turns toward the middle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You leave on the call and meet the dodger before the crease.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You break down, get to his hands, and stop his path to the cage.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "He moves the ball to the player you left.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The second slide and adjacent defenders rotate behind you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You recover to the open player created by the rotation.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You close under control and take away the quick feed inside.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The ball moves back outside, and the defense returns to its shape.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Midfield · next-clear-clean (viz play)
export const CLIP_VIZ_LAX_MIDFIELD_NEXT_CLEAR_CLEAN_SCRIPT: AudioScript = {
  slug: "viz-lax-midfield-next-clear-clean",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself receive the outlet near the sideline and turn upfield.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ride closes the sideline and removes your forward outlet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You force a pass into the middle, and their midfielder intercepts it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Possession changes. You sprint back, communicate, and match up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Later, your defense regains the ball and the outlet comes to you again.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You check the field before the catch and see the sideline pressure coming.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You come back to the ball, move it to the goalie, and cut into space.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The goalie finds the open midfielder, and you fill the next lane.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The ball crosses midfield, and the offense settles into its set.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Defense · lock-him-down (viz play)
export const CLIP_VIZ_LAX_DEFENSE_LOCK_HIM_DOWN_SCRIPT: AudioScript = {
  slug: "viz-lax-defense-lock-him-down",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself pick up the attackman at X with the pole out in front.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He drives topside. You move your feet, stay on his hands, and force him behind the cage.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He tries again. You break down and place one controlled poke on his bottom hand.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You take away his strong hand, and he moves the ball back up top.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On the next dodge, you arrive with the slide and force a low-angle shot the goalie handles.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You approach under control, steer him to his weak hand, and make the slide call early.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "When he gains a step, you recover to his hands without reaching across his body.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The slide stops the ball, and you rotate to the open player.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On a late possession, the attackman isolates at X again.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You maintain leverage, force him to his weak hand, and make him move the ball away from the cage.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Defense · take-it-the-other-way (viz play)
export const CLIP_VIZ_LAX_DEFENSE_TAKE_IT_THE_OTHER_WAY_SCRIPT: AudioScript = {
  slug: "viz-lax-defense-take-it-the-other-way",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the ball spill toward the faceoff wing with the long pole in your hands.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get your hips low, use two hands, and scoop through traffic.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You protect the stick through contact and look for the first outlet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You carry past midfield, draw the short-stick, and move the ball to the open lane.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Next possession, a controlled lift check dislodges the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You scoop it, protect the pole, and identify whether the numbers support transition.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "When the numbers are even, you make the short outlet instead of forcing the carry.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You move the ball, cross midfield, and return to the defensive side through the box.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On the next clear, you scoop a loose ball and move away from the first rider.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You cross midfield with your head up and hit the open midfielder in stride.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Defense · shutdown-1v1-x (viz play)
export const CLIP_VIZ_LAX_DEFENSE_SHUTDOWN_1V1_X_SCRIPT: AudioScript = {
  slug: "viz-lax-defense-shutdown-1v1-x",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself pick up the attackman at X and confirm where your help is.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "With the pole in front, you set your approach angle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He drives topside, and you move your feet to maintain leverage.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stay on his hands and keep your hips between him and GLE.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "With the topside route closed, he rolls back behind the cage.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You arrive first and close the path to GLE.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "A controlled poke moves his hands away from the shooting angle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He moves the ball back up top.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You recover below GLE, check the crease, and call the next matchup.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Defense · slide-recover (viz play)
export const CLIP_VIZ_LAX_DEFENSE_SLIDE_RECOVER_SCRIPT: AudioScript = {
  slug: "viz-lax-defense-slide-recover",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself off-ball, set as the first slide.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Their attackman gains a step toward the crease.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You leave on the call and meet the dodger before the crease.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You close his hands and force him to move the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "He passes to the player you left.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The defense rotates, and you recover to the next open player.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You arrive under control as he receives the pass.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "With the pole on his hands, you take away the feed to the crease.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "He moves the ball outside, and the defense returns to its shape.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Defense · ground-ball-clear (viz play)
export const CLIP_VIZ_LAX_DEFENSE_GROUND_BALL_CLEAR_SCRIPT: AudioScript = {
  slug: "viz-lax-defense-ground-ball-clear",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See a loose ball at the edge of the crease and approach under control.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "An attackman closes from the other side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get low, establish body position, and scoop through the ball with two hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Contact arrives as you bring the stick close to your body.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "With the ball secure, you move behind the cage to create an outlet angle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You protect the pole and move away from the first rider.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get your head up and find the midfielder flashing toward the midline.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You deliver the outlet to his outside shoulder.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The ball crosses midfield, and you set your feet back on the defensive side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Defense · man-down-hold (viz play)
export const CLIP_VIZ_LAX_DEFENSE_MAN_DOWN_HOLD_SCRIPT: AudioScript = {
  slug: "viz-lax-defense-man-down-hold",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself in the man-down shape, protecting the middle of the field.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Their extra-man unit moves the ball around the perimeter.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You sink toward the hole with the stick in the inside passing lane.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "As the ball swings, you rotate with the unit.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You keep the stick up and maintain the crease lane.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "They force the inside feed, and you deflect it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The ball stays loose near the crease.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You scoop through it as the penalty expires.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You move the ball to the outlet and the unit returns to even strength.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Defense · win-next-matchup (viz play)
export const CLIP_VIZ_LAX_DEFENSE_WIN_NEXT_MATCHUP_SCRIPT: AudioScript = {
  slug: "viz-lax-defense-win-next-matchup",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself matched up on a quick dodger at X.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He uses a jab step, gains topside, and reaches GLE.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He finishes the shot before the slide arrives.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The goal is recorded, and you return to the huddle for the next call.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On a later possession, the same dodger starts from X.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You break down earlier and keep a better cushion.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You maintain topside leverage and steer him to his weak hand.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "He cannot reach GLE and moves the ball back up top.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You recover below GLE, check the crease, and prepare for the next dodge.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · FOGO · win-the-clamp (viz play)
export const CLIP_VIZ_LAX_FOGO_WIN_THE_CLAMP_SCRIPT: AudioScript = {
  slug: "viz-lax-fogo-win-the-clamp",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself set your feet at the dot and check your grip and stance.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Down, set. On the whistle, your clamp gets to the ball first.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You control the ball and rake it toward your wing.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your wing scoops through it and moves the ball to the offense.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On the next draw, he counters quickly. You go over the top and stop his exit.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You pull the ball into space, scoop it, and make the short outlet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "When he wins the clamp, you move immediately to the tie-up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You keep the ball contested and direct it toward the wing matchup.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On a late draw, you clamp and direct the ball away from pressure.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You scoop it, protect the stick, and make the outlet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · FOGO · win-the-wing (viz play)
export const CLIP_VIZ_LAX_FOGO_WIN_THE_WING_SCRIPT: AudioScript = {
  slug: "viz-lax-fogo-win-the-wing",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the clamp battle stall and the ball move loose toward the wing.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You keep your hips low, stay connected to the play, and box out the nearest opponent.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your wing scoops through the ball and sends it to the outlet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On the next draw, you direct the ball forward and scoop it in stride.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You carry with your head up and move it to the open lane in transition.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On another tie-up, you and the wing midfielder keep the ball on your side of the scrum.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "After a lost draw, you review the exit and reset your stance.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You prepare for the next whistle without changing the whole plan.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The next ball moves to the wing, and you establish body position between the pole and the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You scoop through it and move the ball to the nearest outlet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · FOGO · counter-the-clamp (viz play)
export const CLIP_VIZ_LAX_FOGO_COUNTER_THE_CLAMP_SCRIPT: AudioScript = {
  slug: "viz-lax-fogo-counter-the-clamp",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself set at the dot, ready with a counter if he beats you to the clamp.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Down, set. On the whistle, his clamp gets to the ball first.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You recognize the loss and move immediately to the counter.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You go over the top and place pressure on the back of his stick.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stop the exit and keep the ball under both sticks.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You re-clamp and pull the ball toward your hand.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You use your body to protect the ball and step away from the dot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your wing moves alongside you as an outlet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You make the short pass and prepare for the next substitution.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Lacrosse · FOGO · win-and-go (viz play)
export const CLIP_VIZ_LAX_FOGO_WIN_AND_GO_SCRIPT: AudioScript = {
  slug: "viz-lax-fogo-win-and-go",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself set at the X with a forward exit available.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Down, set. On the whistle, you clamp and direct the ball forward.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You scoop through it in stride and protect the stick.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You look up and identify the transition numbers.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The trailing midfielder fills the lane behind you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You carry to the top of the box and draw the defender.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "When he commits, you feed the trailing midfielder in stride.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He catches on the run and releases before the slide arrives.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You clear toward the sideline and prepare to sub off.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Lacrosse · FOGO · close-it-out (viz play)
export const CLIP_VIZ_LAX_FOGO_CLOSE_IT_OUT_SCRIPT: AudioScript = {
  slug: "viz-lax-fogo-close-it-out",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself walk to the X for a late draw with your team protecting a lead.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You identify the defensive-side exit and check the wing alignment.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Down, set. On the whistle, you stay low and clamp toward the defensive side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You keep the exit simple and rake the ball away from pressure.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The pole on the wing moves to the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He scoops through it and moves to the outlet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The clear moves up the sideline before the ride can trap it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The offense settles into its possession set and uses the clock.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You return to the sideline and prepare for the next whistle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Lacrosse · FOGO · read-and-adjust (viz play)
export const CLIP_VIZ_LAX_FOGO_READ_AND_ADJUST_SCRIPT: AudioScript = {
  slug: "viz-lax-fogo-read-and-adjust",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself between draws, reviewing the opponent's clamp and exit.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The opponent has favored a quick clamp with an exit to his right.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You choose an over-the-top counter to stop that exit.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Down, set. You remain still and react when the whistle sounds.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "His clamp arrives first, and you move directly to the planned counter.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get over his stick and stop the ball from reaching his exit.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You redirect the ball away from his pressure.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You rake it to space, scoop through it, and protect the stick.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You make the short outlet and record the adjustment for the next draw.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Lacrosse · FOGO · win-the-next-one (viz play)
export const CLIP_VIZ_LAX_FOGO_WIN_THE_NEXT_ONE_SCRIPT: AudioScript = {
  slug: "viz-lax-fogo-win-the-next-one",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself return to the X after losing the previous three draws.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You review the common exit, then focus on this setup.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You adjust the grip and lower the stance without rushing the whistle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Down, set. On the whistle, you get under his hands and clamp.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball stays under your stick as you turn toward the wing.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You rake it toward your wing and away from the counter.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your wing establishes position and scoops through the loose ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball moves to the outlet, and you clear the scrum.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You return to the sideline and prepare for the next draw on its own.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Lacrosse · Goalie · make-the-save (viz play)
export const CLIP_VIZ_LAX_GOALIE_MAKE_THE_SAVE_SCRIPT: AudioScript = {
  slug: "viz-lax-goalie-make-the-save",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself set the angle in the cage and check the shooter's hands.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The shooter winds up from twelve yards, and you track the release off the stick.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You step toward the ball, drive both hands stick-side high, and control it in the pocket.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You secure the ball and look immediately for the first outlet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Next possession, a low bouncer comes through traffic. You stay square and get the stick to the ball first.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your body follows the stick, and you control the rebound in front of you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On a later shot, the ball reaches the net before you get across.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You retrieve it, reset your feet, and make the defensive calls for the restart.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On the next crease feed, you hold the angle and step toward the shooter's hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You meet the shot with stick and body and steer the rebound toward the pole in the corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Goalie · start-the-clear (viz play)
export const CLIP_VIZ_LAX_GOALIE_START_THE_CLEAR_SCRIPT: AudioScript = {
  slug: "viz-lax-goalie-start-the-clear",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself set in the cage, calling the hot defender and the second slide.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The shot comes from up top, and you secure it in the pocket.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your eyes move upfield as the break midfielder runs the wing.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You deliver the outlet in stride before the ride can close the lane.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On the next clear, the ride takes away the first pass, so you carry behind the cage and keep scanning.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You call the redirect and find the defender on the weak side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "When a clear is ridden into a turnover, you communicate the matchups immediately.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You reset the defense, call the next slide, and set your angle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On the next save, you control the ball and return to the simple outlet on the wing.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The outlet crosses midfield, and you return to the crease.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Lacrosse · Goalie · doorstep (viz play)
export const CLIP_VIZ_LAX_GOALIE_DOORSTEP_SCRIPT: AudioScript = {
  slug: "viz-lax-goalie-doorstep",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself set in the crease as the ball moves inside.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Their attackman catches on the crease, five feet from the cage.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You hold the angle instead of retreating toward the goal line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You step toward his hands and reduce the open cage.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You track the head of his stick through the release.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Both hands drive to the ball, with your body behind the stick.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You control the ball against your chest and keep it in the pocket.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You check the crease and wait for the outlet to separate.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You make the outlet call and begin the clear.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Lacrosse · Goalie · low-bouncer (viz play)
export const CLIP_VIZ_LAX_GOALIE_LOW_BOUNCER_SCRIPT: AudioScript = {
  slug: "viz-lax-goalie-low-bouncer",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself set square to a shooter winding up from ten yards.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "His hands drop through the release, and you track the ball low.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The shot is aimed to bounce near your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You keep your eyes on the ball and step toward the bounce.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The stick arrives first, with both hands driving toward the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stay square so the body follows directly behind the stick.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball settles in front of you without a rebound to the crease.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You scoop it, bring the stick to protection, and check the outlets.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You reset your feet and make the clear call.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Lacrosse · Goalie · man-down-kill (viz play)
export const CLIP_VIZ_LAX_GOALIE_MAN_DOWN_KILL_SCRIPT: AudioScript = {
  slug: "viz-lax-goalie-man-down-kill",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself in the cage with a defender serving a penalty.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Their extra-man unit moves the ball around the perimeter.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You move on your arc and stay square to each catch.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The first shot comes from up top, and you direct the rebound to the corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The defense moves the rebound up the sideline while the penalty continues.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On the next possession, the ball moves skip-side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You read the feed to the crease and set the angle before the catch.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You step to the release and control the ball without a rebound.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The penalty expires, and you make the outlet as the team returns to even strength.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Lacrosse · Goalie · command-the-defense (viz play)
export const CLIP_VIZ_LAX_GOALIE_COMMAND_THE_DEFENSE_SCRIPT: AudioScript = {
  slug: "viz-lax-goalie-command-the-defense",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself set in the middle of the crease with the offense arranged around you.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Their attackman catches at X, and you identify the on-ball matchup.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You call the hot defender and the second slide before the dodge begins.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He dodges, and the first slide leaves on your call.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You call the rotation, and the adjacent defenders fill behind the slide.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball moves outside as the defense returns to its shape.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The offense forces a feed inside, and the pole intercepts it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You call the clear as the pole moves the ball away from the crease.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You return to your angle and organize the outlets.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Lacrosse · Goalie · next-save (viz play)
export const CLIP_VIZ_LAX_GOALIE_NEXT_SAVE_SCRIPT: AudioScript = {
  slug: "viz-lax-goalie-next-save",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself return to the crease after a shot you expected to save reaches the net.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The goal is recorded. You retrieve the ball and reset the cage.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You set your feet on the arc and establish the angle early.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You call the hot defender and the second slide for the restart.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The next shot comes from the wing.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stay square with both hands ready and track the release.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You step toward the shot and drive the stick to the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You control the ball against your chest.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You secure the ball and give the first outlet call.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// ── Exports ───────────────────────────────────────────────────────────────

export const LACROSSE_VIZ_CLIP_SCRIPTS: AudioScript[] = [
  CLIP_VIZ_LAX_ATTACK_SCRIPT,
  CLIP_VIZ_LAX_MIDFIELD_SCRIPT,
  CLIP_VIZ_LAX_DEFENSE_SCRIPT,
  CLIP_VIZ_LAX_FOGO_SCRIPT,
  CLIP_VIZ_LAX_GOALIE_SCRIPT,
  CLIP_VIZ_LAX_ATTACK_BEAT_YOUR_MAN_SCRIPT,
  CLIP_VIZ_LAX_ATTACK_SEE_THE_FIELD_SCRIPT,
  CLIP_VIZ_LAX_ATTACK_FINISH_ON_CREASE_SCRIPT,
  CLIP_VIZ_LAX_ATTACK_TIME_AND_ROOM_SCRIPT,
  CLIP_VIZ_LAX_ATTACK_RIDE_FORCE_TURNOVER_SCRIPT,
  CLIP_VIZ_LAX_ATTACK_MAN_UP_FINISH_SCRIPT,
  CLIP_VIZ_LAX_ATTACK_NEXT_LOOK_CLEAN_SCRIPT,
  CLIP_VIZ_LAX_MIDFIELD_PUSH_THE_BALL_SCRIPT,
  CLIP_VIZ_LAX_MIDFIELD_COVER_BOTH_ENDS_SCRIPT,
  CLIP_VIZ_LAX_MIDFIELD_SHOOT_ON_THE_RUN_SCRIPT,
  CLIP_VIZ_LAX_MIDFIELD_BOTH_ENDS_SHIFT_SCRIPT,
  CLIP_VIZ_LAX_MIDFIELD_GROUND_BALL_SCRUM_SCRIPT,
  CLIP_VIZ_LAX_MIDFIELD_SLIDE_AND_ROTATE_SCRIPT,
  CLIP_VIZ_LAX_MIDFIELD_NEXT_CLEAR_CLEAN_SCRIPT,
  CLIP_VIZ_LAX_DEFENSE_LOCK_HIM_DOWN_SCRIPT,
  CLIP_VIZ_LAX_DEFENSE_TAKE_IT_THE_OTHER_WAY_SCRIPT,
  CLIP_VIZ_LAX_DEFENSE_SHUTDOWN_1V1_X_SCRIPT,
  CLIP_VIZ_LAX_DEFENSE_SLIDE_RECOVER_SCRIPT,
  CLIP_VIZ_LAX_DEFENSE_GROUND_BALL_CLEAR_SCRIPT,
  CLIP_VIZ_LAX_DEFENSE_MAN_DOWN_HOLD_SCRIPT,
  CLIP_VIZ_LAX_DEFENSE_WIN_NEXT_MATCHUP_SCRIPT,
  CLIP_VIZ_LAX_FOGO_WIN_THE_CLAMP_SCRIPT,
  CLIP_VIZ_LAX_FOGO_WIN_THE_WING_SCRIPT,
  CLIP_VIZ_LAX_FOGO_COUNTER_THE_CLAMP_SCRIPT,
  CLIP_VIZ_LAX_FOGO_WIN_AND_GO_SCRIPT,
  CLIP_VIZ_LAX_FOGO_CLOSE_IT_OUT_SCRIPT,
  CLIP_VIZ_LAX_FOGO_READ_AND_ADJUST_SCRIPT,
  CLIP_VIZ_LAX_FOGO_WIN_THE_NEXT_ONE_SCRIPT,
  CLIP_VIZ_LAX_GOALIE_MAKE_THE_SAVE_SCRIPT,
  CLIP_VIZ_LAX_GOALIE_START_THE_CLEAR_SCRIPT,
  CLIP_VIZ_LAX_GOALIE_DOORSTEP_SCRIPT,
  CLIP_VIZ_LAX_GOALIE_LOW_BOUNCER_SCRIPT,
  CLIP_VIZ_LAX_GOALIE_MAN_DOWN_KILL_SCRIPT,
  CLIP_VIZ_LAX_GOALIE_COMMAND_THE_DEFENSE_SCRIPT,
  CLIP_VIZ_LAX_GOALIE_NEXT_SAVE_SCRIPT,
];
