// FV-136 positive-play visualization clips.
//
// 52 discrete viz-<position>-<play> AudioScript exports, one per scenario in
// docs/pregame-scripts.md §1. Texts are verbatim from the finalized md
// (KC-edited, §3-reviewer-finalized). Do NOT paraphrase.
//
// Each scenario = numbered speech lines + trailing silence per [Ns] beat,
// exactly mirroring the md. No added intro/outro — the runtime playlist
// stitches opener → viz → hm → closing. Phase mark "rink" on the first
// segment (consistent with the existing *_VIZ convention in segments.ts).
//
// All clips: voice ash, speed 0.95, SCRIPT_INSTRUCTIONS, CLIP_LOUDNORM_FILTER.
// Replace the monolithic FORWARD_VIZ / DEFENSE_VIZ / GOALIE_VIZ / *_VIZ
// blocks in the template with a per-play discrete slug. The v2 picker
// (FV-144) is purely additive — no resolver change needed.

import type { AudioScript } from "./types";
import { SCRIPT_INSTRUCTIONS, VISUALIZATION_INSTRUCTIONS } from "./instructions.ts";
import { CLIP_LOUDNORM_FILTER } from "./loudnorm";

// ── Defense — Hockey (9 plays) ───────────────────────────────────────────────

export const CLIP_VIZ_DEFENSE_RETRIEVAL_SCRIPT: AudioScript = {
  slug: "viz-defense-retrieval",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself as the first player back, on your toes and ready for it.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The puck is dumped in behind you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You shoulder-check over your inside shoulder.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You turn and sprint back for it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You shoulder-check again — you know where the forecheck is.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You feel him coming, but you are not rushed.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "At the puck, you sell up the wall.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The forechecker leans. You cut back into space.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Clean pickup, head up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Tape-to-tape pass to your winger.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_DEFENSE_WALK_THE_LINE_SCRIPT: AudioScript = {
  slug: "viz-defense-walk-the-line",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the puck come to you at the blue line, with the whole play in front of you.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The puck rims around the wall to you at the point.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "It's bouncing — you settle it down.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You pull it off the wall, along the blue line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You open up, eyes on the lane.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "A teammate ties up the net-front.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You walk the line one more step, into the seam.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You fire it through — a hard shot, on net, low.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Stick on the ice for the rebound.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_DEFENSE_GAP_UP_SCRIPT: AudioScript = {
  slug: "viz-defense-gap-up",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the rush coming at you, and feel yourself ready to control the space.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "They break out, you swing back.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You skate it backward, eyes on the puck carrier's chest.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You close your gap — one stick-length, then tighter.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "He tries to beat you wide.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You match his speed, angle him to the wall.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You stand him up at the line. No entry.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The puck dies in the corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your partner is there. You win it back.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_DEFENSE_BREAKOUT_SCRIPT: AudioScript = {
  slug: "viz-defense-breakout",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself below the goal line, pressure coming, eyes up and ready to move it.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You retrieve it low, under pressure from F1.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You shoulder-check — F2 is reading your first option.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You take it behind the net, holding the puck.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "D-to-D, hard pass to your partner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He's got a step now, the forecheck overcommitted.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You skate to support, an option up the wall.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He hits you in stride at the hash marks.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You chip it out, clean. Zone exit, on the tape.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_DEFENSE_LONG_SHIFT_SCRIPT: AudioScript = {
  slug: "viz-defense-long-shift",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself late in a hard shift, tired but still responsible.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "They keep it in at your line — you can't get the clear.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The shift gets long. They cycle low and you're pinned in your zone.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your legs are burning. You want the change. It's not there yet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stay above your check. Box out. Battle for body position.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You don't cheat for offense — you defend, take away the next pass.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The puck squirts loose to your corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get to it, shoulder-check, and chip it hard off the glass and out.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Clean clear. You're first to the bench.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Fresh legs jump on. Long shift, no goal against.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You did your job. That's the change you earned.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_DEFENSE_PINCH_SCORE_SCRIPT: AudioScript = {
  slug: "viz-defense-pinch-score",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the puck near the wall and know this is your chance to keep the play alive.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The puck's chipped up the wall, trying to leave the zone.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You're the D at the blue line. You read it early.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You shoulder-check — your center is high, covering for you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You step down and pinch, pin it on the wall.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You win the battle and knock it to the middle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You walk off the wall into the slot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You snap a low shot through the traffic.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "It tips in. You kept it alive and buried it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_DEFENSE_PENALTY_KILL_CLEAR_SCRIPT: AudioScript = {
  slug: "viz-defense-penalty-kill-clear",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself on the penalty kill, locked into your lane and your job.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You are on the penalty kill. They set up high.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stay in the shot lane, stick out front.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The puck moves to the half wall. You do not chase.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You keep the box tight and protect the middle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The shot comes from the point. You get in the lane.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "It hits your shin pad and drops loose.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You win the race and chip it hard down the ice.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Your bench taps their sticks. Kill the next one.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_DEFENSE_VOCAL_BREAKOUT_SCRIPT: AudioScript = {
  slug: "viz-defense-vocal-breakout",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself as the calm voice on the ice, helping everyone play faster.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your partner goes back for the puck.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You shoulder-check and read the forecheck.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You call it early: \"Reverse.\"", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He hears you and banks it behind the net.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You collect it in stride, head up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The winger is posted on the wall. Your center is low.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You call \"wall\" and put it on the tape.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Clean exit. Your voice made the game slower.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_DEFENSE_ANGLE_WIDE_BOXOUT_SCRIPT: AudioScript = {
  slug: "viz-defense-angle-wide-boxout",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the rush building, and feel yourself set, square, and ready to angle him off.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "They come through the neutral zone with speed.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You hold the middle and match his pace.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You do not lunge. You do not open the inside lane.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You angle him wide toward the boards.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "He shoots from outside the dot. Low danger.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your goalie makes the save. The rebound drops in front.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You tie up his stick and take his body.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your partner collects the puck.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Middle protected. Rebound won. Job done.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// ── Forward — Hockey (10 plays) ──────────────────────────────────────────────

export const CLIP_VIZ_FORWARD_WIN_THE_WALL_SCRIPT: AudioScript = {
  slug: "viz-forward-win-the-wall",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the puck go into your corner and know you are going to win the race.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The puck's chipped into your corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get there first, low and strong.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You take the body, pin your check, protect the puck.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You pull it off the wall to the middle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You drive the net, hard, inside hand.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You go to the backhand, around the goalie's pad.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The puck crosses the line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The puck is in. You earned that one.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_FORWARD_GIVE_AND_GO_SCRIPT: AudioScript = {
  slug: "viz-forward-give-and-go",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See open ice ahead of you and feel your speed starting to build.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You carry it through the neutral zone, speed building.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You shoulder-check — your winger is filling the lane.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You give it to him and accelerate.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You hit the soft spot in the D, between the two defenders.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "His return pass is on your tape, flat.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "One touch to settle it, the goalie sliding.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You roof it over the blocker.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Top corner. Bar down.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_FORWARD_BACKCHECK_STRIP_SCRIPT: AudioScript = {
  slug: "viz-forward-backcheck-strip",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the turnover happen and feel yourself commit to getting back hard.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The puck turns over at their blue line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "They're on the rush, you're the high forward.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You turn and skate, full speed, back through center.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You track the puck-carrier on his inside hand.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You catch him at the top of the circle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Active stick — you lift his, then poke the puck free.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You knock it to the corner, kill the rush.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You jump back to the bench. Clean change.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_FORWARD_NET_FRONT_SCRIPT: AudioScript = {
  slug: "viz-forward-net-front",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself at the net-front, ready to make a hard play in traffic.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The point man winds up for the shot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You set up at the net-front, stick on the ice.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You find a lane, body between the D and the goalie.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The shot comes — you get a piece, tip it down.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The goalie kicks out a rebound.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You're already on it, hands quick.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You bang it home before he resets.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The puck is in. Net-front work paid off.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_FORWARD_FACEOFF_WIN_SHOT_SCRIPT: AudioScript = {
  slug: "viz-forward-faceoff-win-shot",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself over the dot, set, calm, and ready for the puck drop.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You're at the dot in the O-zone. You set your grip.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You read the linesman's hand. You win it clean back to your D.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You release off the dot and find the soft ice in the slot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your D walks the line and the lane opens.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The puck comes down to the tape in the middle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "One touch, you bury it bar-down.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_FORWARD_2ON1_PASS_FINISH_SCRIPT: AudioScript = {
  slug: "viz-forward-2on1-pass-finish",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the odd-man rush opening up, with space and speed in front of you.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You jump the gap and it's a 2-on-1 the other way.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You read the D — he sinks to take the pass.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You're patient. You drive the soft ice and hold the puck.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He commits to you. The lane to your winger opens.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You slide it flat across, right onto his tape.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He one-times it home. You made that play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_FORWARD_FORECHECK_STRIP_SCRIPT: AudioScript = {
  slug: "viz-forward-forecheck-strip",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself as F1, first into the zone, setting the pressure.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You're F1, first man in on the forecheck.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You take the right angle and cut off his strong-side option.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You close hard and pin him to the wall.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You lift his stick and steal the puck off the boards.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You spin off pressure, low to the net.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You tuck it short side. Forecheck to goal.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_FORWARD_CYCLE_LOW_HIGH_SCRIPT: AudioScript = {
  slug: "viz-forward-cycle-low-high",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the puck below the goal line and feel your line ready to build pressure.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The puck is below the goal line. You get there first.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You protect it with your body, shoulder into pressure.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You hear your teammate call for the cycle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You leave it soft off the wall and roll high.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The puck moves low to high to your D.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You drive through the defender's hands to the net-front.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The shot comes through traffic.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You screen the goalie and hunt the rebound.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Possession kept. Pressure built. That is winning hockey.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_FORWARD_3ON2_MIDDLE_DRIVE_SCRIPT: AudioScript = {
  slug: "viz-forward-3on2-middle-drive",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the rush forming, and know your middle-lane drive can open everything.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You cross the red line with speed. It is a 3-on-2.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your winger has the puck wide. You read the gap.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You drive the middle lane hard, stick on the ice.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Both defenders feel you coming through the slot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The far winger delays into open ice.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The pass goes across. The shot comes.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You stop at the net-front, ready for the rebound.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The puck kicks loose. You bury it from the top of the crease.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_FORWARD_DZONE_FACEOFF_WIN_SCRIPT: AudioScript = {
  slug: "viz-forward-dzone-faceoff-win",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the defensive-zone draw and feel the importance of doing your job.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Defensive-zone draw. Late in the period.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You set your feet and know your job.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The puck drops. You tie up hard.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your winger jumps through and wins the loose puck.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You support low and protect the middle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The puck goes wall-side, then out.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You clear the zone and get fresh legs on.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Small play. Big moment. You did your job.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// ── Goalie — Hockey (9 plays) ────────────────────────────────────────────────

export const CLIP_VIZ_GOALIE_TRACK_AND_SAVE_SCRIPT: AudioScript = {
  slug: "viz-goalie-track-and-save",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the play enter your zone and feel yourself settled in your crease.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The puck comes up the wall into the zone.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You set your depth, square to the puck.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stay big, hands out front, weight on the balls of your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The shooter loads up from the top of the circle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You track it off his blade, all the way in.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You take it in the chest, smother it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The whistle blows. You've got it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You're calm. Set for the next one.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_GOALIE_REBOUND_CONTROL_SCRIPT: AudioScript = {
  slug: "viz-goalie-rebound-control",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the shooter on the wing and feel yourself ready to control the puck.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Shot from the wing, low and hard.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You drop into your butterfly, sealed to the ice.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You take it off the pad.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You angle the pad, steer the rebound to the corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "No second chance — the puck dies in the boards.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You push back to your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You re-center on your post, depth set.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Eyes back on the puck. Next shot only.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_GOALIE_POST_TO_POST_SCRIPT: AudioScript = {
  slug: "viz-goalie-post-to-post",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the puck below the goal line and feel yourself sealed and patient.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The puck swings low, below the goal line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You seal the near post, leak nothing short side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The pass goes cross-ice, backdoor.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You push post to post, square on arrival.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You're set before the shot — not sliding through it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You take it on the blocker, controlled.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You direct it high glass, out of danger.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You reset to center. You held your ground.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_GOALIE_BREAKAWAY_SCRIPT: AudioScript = {
  slug: "viz-goalie-breakaway",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the player coming in alone and feel your body stay big and quiet.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He's behind the D, in alone, gathering speed.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You set your depth at the top of the crease.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You match his pace as he comes, staying patient.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Stay big. Hands out front. Don't bite on the first move.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "He pulls it to his forehand, tries to go five-hole.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stay on your feet, then close the seal.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The puck hits your pads and dies.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You cover it up. You won that one-on-one.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_GOALIE_GLOVE_FREEZE_SCRIPT: AudioScript = {
  slug: "viz-goalie-glove-freeze",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the shot developing through traffic and feel your glove ready out front.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Puck's in the corner, they're working it for a shot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You're square, gloves out front, tracking it through.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The shot comes hard, glove side, high.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You catch it clean. The leather snaps shut.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You hold it. The whistle goes.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stayed square. You held it. Faceoff.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_GOALIE_SCRAMBLE_SAVE_SCRIPT: AudioScript = {
  slug: "viz-goalie-scramble-save",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the crease get messy and know you are going to keep fighting for the puck.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "It's a scramble in your crease. The puck's loose.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The first shot beats you and you're down and out.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You don't quit on it. You drive to your post.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You throw the pad across and seal the ice.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The puck hits you and stays out.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You found it, you covered it. Whistle. Breathe.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_GOALIE_SCREEN_TRAFFIC_SCRIPT: AudioScript = {
  slug: "viz-goalie-screen-traffic",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See bodies in front of you and feel yourself working to find the puck.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "There's a shot coming and a body in your sightline.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You don't fight the screen. You move to find the puck.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You drop and look around the hip, eyes on the release.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You see it late and get a piece — it's off your chest.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You smother the rebound before a stick can find it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You read it through the traffic. Save and freeze.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_GOALIE_PLAY_PUCK_BREAKOUT_SCRIPT: AudioScript = {
  slug: "viz-goalie-play-puck-breakout",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the dump-in coming and know you can help your team before pressure arrives.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The puck is dumped in hard around the glass.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You leave your crease and get behind it early.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stop it clean behind the net.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You shoulder-check. F1 is coming.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You make the simple play to your defenseman's forehand.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He collects it with time. The forecheck slows down.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You get back to your crease, square and ready.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You helped your team break out before the pressure arrived.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_GOALIE_PK_SEAM_SAVE_SCRIPT: AudioScript = {
  slug: "viz-goalie-pk-seam-save",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the power play moving the puck and feel yourself patient through the seam.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "They are on the power play, moving the puck around the outside.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stay patient, square to the puck.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The pass goes across the seam.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You push hard, eyes arriving before your body.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get set on your edge before the release.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The one-timer comes. You take it in the chest.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "No rebound. Whistle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You stayed patient. You beat the pass.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// ── Guard — Basketball (8 plays) ─────────────────────────────────────────────

export const CLIP_VIZ_GUARD_PICK_AND_ROLL_SCRIPT: AudioScript = {
  slug: "viz-guard-pick-and-roll",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself bringing the ball up, calm, with the floor spread in front of you.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You bring it up, eyes on the floor.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You call for the screen. Your big climbs up to set it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You wait for the screen to hit. You do not leave early.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You snake off the pick, shoulder past his man.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The big drops back in coverage.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You see the gap open in the lane.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get downhill, two feet in the paint.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The low defender steps toward you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You read it calmly — finish if he stays, pass if he commits.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Tonight, he stays. You lay it in soft off the glass.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Good read. Good pace. Next possession.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_GUARD_TRANSITION_PULLUP_SCRIPT: AudioScript = {
  slug: "viz-guard-transition-pullup",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the rebound hit your hands and feel the floor open in transition.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You snatch the rebound and push.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You see numbers, and the defense is backpedaling.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "One dribble, two, eating up the floor.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The defender keeps giving ground.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You feel your feet hit the spot just inside the line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You rise up, balanced, eyes on the rim.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Clean release.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "It drops.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You sprint back, already talking on defense.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_GUARD_LIVE_STEAL_SCRIPT: AudioScript = {
  slug: "viz-guard-live-steal",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself picking up full court, low, active, and ready to pressure.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You pick up your man full court.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You're in a stance, chest in front, feet active.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He tries to turn the corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You cut him off with your chest, not your hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He puts his head down to dribble.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You time the bounce, dig down once, and knock it loose.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You scoop it on the run, no one between you and the rim.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You finish it strong on the other end.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Feet first. Hands second. Clean defense.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_GUARD_DRIVE_AND_KICK_SCRIPT: AudioScript = {
  slug: "viz-guard-drive-and-kick",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the closeout coming and know you are ready to attack the advantage.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You catch it at the top, your man closes out hard.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You rip through and attack his front foot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You turn the corner, downhill into the paint.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The low man slides over to stop the drive.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You see your shooter spot up in the corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You hang, draw the second defender.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You whip the kick-out on a rope.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He catches it in rhythm and buries it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You created the shot by making the right read.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_GUARD_PRESS_BREAK_SCRIPT: AudioScript = {
  slug: "viz-guard-press-break",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the press coming at you, and feel yourself calm with the ball.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "They pick you up full court.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You come back to the ball, low and strong.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Two defenders start to shade you toward the sideline.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You do not panic.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You retreat dribble once and create space.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Your teammate flashes to the middle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You hit him on time, away from pressure.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball moves ahead. The press is broken.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You sprint into spacing and get the team organized.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Calm with the ball. Simple play. Pressure handled.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_GUARD_RUN_THE_SET_SCRIPT: AudioScript = {
  slug: "viz-guard-run-the-set",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the game speeding up and feel yourself ready to settle the team.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The game is speeding up. Your team needs a good possession.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You bring it across half court under control.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You raise your hand and call the set.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You move the ball early and cut through.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball reverses. The defense shifts.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get it back and make the simple read.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your teammate gets a clean look in rhythm.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Good possession. You led without forcing.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_GUARD_CLUTCH_FREE_THROWS_SCRIPT: AudioScript = {
  slug: "viz-guard-clutch-free-throws",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself at the line in a tight game, with your routine ready.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Tie game, under ten seconds, you drive hard and the whistle blows.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Two shots. The other gym is loud behind the rim.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You step to the line and the ref hands you the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Three dribbles, spin it, breath out — your routine, the same every time.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Legs are tired, but you bend your knees and use them anyway.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Eyes on the back of the rim.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "First one is pure.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Same breath, same hold.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Second one drops through.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You backpedal on defense, calm and ready for the next stop.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_GUARD_ICES_IT_LATE_SCRIPT: AudioScript = {
  slug: "viz-guard-ices-it-late",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the trap coming late, and feel yourself strong with the ball.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Up two, final seconds, and they trap you full-court to take the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Two defenders come hard — you stay low, protect the ball, and do not panic.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You keep your dribble alive and get fouled.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "They have to put you on the line to stop the clock.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Bonus, two shots. You walk up calm.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Routine, breath, eyes up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "First one is good.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Same rhythm. Second one through.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Game is not over because you celebrated. Game is over because you took care of the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// ── Wing — Basketball (8 plays) ──────────────────────────────────────────────

export const CLIP_VIZ_WING_CATCH_AND_SHOOT_SCRIPT: AudioScript = {
  slug: "viz-wing-catch-and-shoot",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself spaced on the wing, ready before the ball arrives.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You space to the wing, ready.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball swings around the horn.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your feet are ready before the ball arrives. Hands up, knees loaded.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The pass hits your hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The closeout flies at you a beat too late.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You go straight up into your shot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Smooth release over the contest.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You hold your follow-through.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "It drops, and you sprint back on defense.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_WING_ATTACK_CLOSEOUT_SCRIPT: AudioScript = {
  slug: "viz-wing-attack-closeout",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the skip pass coming and feel the closeout flying at you.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The skip pass finds you on the wing.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You shot-fake. Your man flies by, out of control.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You rip through and put it on the floor, downhill.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Two dribbles into the gap, into the paint.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The big steps up off your roller.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You read his chest. If he stays back, you finish. If he steps up, you drop it off.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Tonight, he is late.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You gather under the rim.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You finish high off the glass through contact.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Strong attack. Right read.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_WING_DENIAL_DEFLECTION_SCRIPT: AudioScript = {
  slug: "viz-wing-denial-deflection",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See your matchup trying to get open, and feel yourself locked into the lane.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your man wants the ball on the wing.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You're in the passing lane, hand in, denying.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You feel him cut, and you stay attached — ball, you, man.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The pass comes anyway, lazy, into the gap.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You jump the lane and deflect it loose.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You corral it and turn upcourt.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You push it ahead.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your team gets a clean finish on the break.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Defense created offense.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_WING_BACKDOOR_CUT_SCRIPT: AudioScript = {
  slug: "viz-wing-backdoor-cut",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See your defender overplaying, and feel the backdoor lane open.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You're on the wing, and your man overplays the pass.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You feel him cheat, top hand in the lane.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You plant hard and cut backdoor behind him.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You flash open down the lane, hand ready.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The bounce pass leads you to the rim.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You catch it in stride.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "One step, eyes up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You finish at the rim before the help arrives.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You did not stand. You cut with purpose.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_WING_CLOSEOUT_CONTAIN_SCRIPT: AudioScript = {
  slug: "viz-wing-closeout-contain",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the ball skip to the corner and feel yourself ready to close out under control.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball skips to your man in the corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You sprint the first steps, then chop your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "High hand. No fly-by.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He shot-fakes. You stay down.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "He drives baseline.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You slide and cut him off.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "He picks up the ball with nowhere to go.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You contest the pass and your team resets the defense.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Disciplined closeout. No foul. No blow-by.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_WING_RELOCATE_CATCH_SHOOT_SCRIPT: AudioScript = {
  slug: "viz-wing-relocate-catch-shoot",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself move after the pass, staying active and ready.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You catch on the wing and the closeout comes hard.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You make the simple pass to the top.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You do not stand and watch.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You slide to the corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your hands are ready. Your feet are already set.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball swings back to you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You catch in rhythm, eyes on the rim.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Smooth release.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "It drops, and you sprint back on defense.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Pass. Move. Be ready.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_WING_CLUTCH_FREE_THROWS_SCRIPT: AudioScript = {
  slug: "viz-wing-clutch-free-throws",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself at the line on the road, with the gym trying to shake you.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Late in a road game, you catch on the wing and rise into your jumper.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "It falls, and the contact comes — and-1.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The home crowd gets loud, trying to pull you out of your routine.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You step up, settle your feet, and let the noise wash past you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "One dribble, deep breath, the same stroke you shoot in an empty gym.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Elbow in, follow through, hold it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Bottom of the net.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You turn and sprint back, calm and locked in.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_WING_LATE_JUMPER_SCRIPT: AudioScript = {
  slug: "viz-wing-late-jumper",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the ball find you late, with space to rise into your shot.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Under thirty seconds, a one-possession game, the ball finds you on the wing.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your man flies at the closeout, hand up, trying to run you off the line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "One hard jab.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You rise up clean over the contest.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Elbow in, eyes on the rim, the same shot you have practiced over and over.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "It leaves your hand soft, perfect rotation.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "It drops clean.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You turn and sprint back, already onto the next stop.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// ── Big — Basketball (8 plays) ───────────────────────────────────────────────

export const CLIP_VIZ_BIG_ROLL_AND_FINISH_SCRIPT: AudioScript = {
  slug: "viz-big-roll-and-finish",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself sprinting into the screen, ready to create contact and roll hard.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You climb up and set a wall of a screen.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your guard rubs his man off you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You feel the hit, then you roll hard to the rim.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The low man tags you, then recovers out.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You're open, sealing down the middle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The pocket pass hits you on the roll.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You catch it on the move.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Two feet. Strong base.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You go up strong through the contact.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball drops. Strong finish.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_BIG_POST_SEAL_DROPSTEP_SCRIPT: AudioScript = {
  slug: "viz-big-post-seal-dropstep",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself beating your man down the floor and earning deep position.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You sprint the floor and beat your man down.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You did the work before the catch.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You sit him on your back, seal deep, hands high.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your guard hits you on the block.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You feel where he is playing you — high side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You drop step baseline into the open lane.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "One strong dribble, into your body.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You go up off two feet and finish over him.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Early work. Deep catch. Strong finish.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_BIG_BOXOUT_OUTLET_SCRIPT: AudioScript = {
  slug: "viz-big-boxout-outlet",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the shot go up and feel yourself ready to own the glass.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The shot goes up from the wing.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You find your man, put a body on him, and hit him first.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You feel him try to slip around.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stay attached.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball comes off long to your side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You go get it at its highest point, two hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You land, chin it, and pivot away from pressure.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You see your guard leaking out.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You hit the outlet ahead and start the break.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The possession ends because you did your work on the glass.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_BIG_RIM_PROTECT_AND_GO_SCRIPT: AudioScript = {
  slug: "viz-big-rim-protect-and-go",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the guard coming downhill and feel yourself ready to protect the rim.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Their guard turns the corner, downhill at you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You're in drop coverage, walling up the paint.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You hold your ground, feet set, chest square.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "He gathers and goes up at the rim.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You meet him vertical, hands high, no reach.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "He has to finish over length.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The shot comes off.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You secure it with two hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Outlet ahead. Your stop started the break.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_BIG_RESCREEN_ROLL_SCRIPT: AudioScript = {
  slug: "viz-big-rescreen-roll",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself coming into the screen with purpose, ready to create an advantage.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You sprint into the screen, feet set, wide base.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your guard waits until you make contact.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The defender fights over the top.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You turn and re-screen, changing the angle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Now your guard gets downhill.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You roll hard into the open lane.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The help steps up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your teammate gets the corner three.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your screen created the shot. That is winning basketball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_BIG_SHORT_ROLL_READ_SCRIPT: AudioScript = {
  slug: "viz-big-short-roll-read",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the defense step toward your guard and feel the pocket open for you.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You set the screen high. Your guard turns the corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Both defenders step toward him.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You slip into the pocket, hands ready.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The pass hits you at the free-throw line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You land on two feet and read the low man.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "He steps up to stop you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You drop the pass to your teammate under the rim.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Easy finish.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You made the right read.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

export const CLIP_VIZ_BIG_CLUTCH_FREE_THROWS_SCRIPT: AudioScript = {
  slug: "viz-big-clutch-free-throws",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself at the line late, with everyone expecting the miss.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "They put you on the line on purpose, late, hoping you'll miss.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The whole gym knows the plan.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You step up slow, set your feet wide, and breathe it all the way down.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Spin the ball, find your line, same routine you grind after every practice.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You shot these when no one was watching.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Push it soft off the fingertips.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "First one drops.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Same motion, no rush.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Second one falls clean.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You did your job. Now get back and protect the paint.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

export const CLIP_VIZ_BIG_GAME_SEALING_BLOCK_SCRIPT: AudioScript = {
  slug: "viz-big-game-sealing-block",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the final possession coming at the rim, and feel yourself ready to wall up.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Final possession, you're guarding the rim, protecting a two-point lead.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Their guard turns the corner and comes downhill at you full speed.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You slide over, feet set, hands straight up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Vertical. No reach.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "He goes up to finish.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You wall up, stay vertical, and take away the finish.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "All contest. No whistle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The rebound falls to your hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You rip it down strong.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Outlet it ahead, and the game is yours.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// ── All 52 viz clip scripts, ordered: defense (9) + forward (10) + goalie (9) +
//    guard (8) + wing (8) + big (8). Used by generate-pregame-audio.ts.
export const VIZ_CLIP_SCRIPTS: AudioScript[] = [
  // Defense — 9 plays
  CLIP_VIZ_DEFENSE_RETRIEVAL_SCRIPT,
  CLIP_VIZ_DEFENSE_WALK_THE_LINE_SCRIPT,
  CLIP_VIZ_DEFENSE_GAP_UP_SCRIPT,
  CLIP_VIZ_DEFENSE_BREAKOUT_SCRIPT,
  CLIP_VIZ_DEFENSE_LONG_SHIFT_SCRIPT,
  CLIP_VIZ_DEFENSE_PINCH_SCORE_SCRIPT,
  CLIP_VIZ_DEFENSE_PENALTY_KILL_CLEAR_SCRIPT,
  CLIP_VIZ_DEFENSE_VOCAL_BREAKOUT_SCRIPT,
  CLIP_VIZ_DEFENSE_ANGLE_WIDE_BOXOUT_SCRIPT,
  // Forward — 10 plays
  CLIP_VIZ_FORWARD_WIN_THE_WALL_SCRIPT,
  CLIP_VIZ_FORWARD_GIVE_AND_GO_SCRIPT,
  CLIP_VIZ_FORWARD_BACKCHECK_STRIP_SCRIPT,
  CLIP_VIZ_FORWARD_NET_FRONT_SCRIPT,
  CLIP_VIZ_FORWARD_FACEOFF_WIN_SHOT_SCRIPT,
  CLIP_VIZ_FORWARD_2ON1_PASS_FINISH_SCRIPT,
  CLIP_VIZ_FORWARD_FORECHECK_STRIP_SCRIPT,
  CLIP_VIZ_FORWARD_CYCLE_LOW_HIGH_SCRIPT,
  CLIP_VIZ_FORWARD_3ON2_MIDDLE_DRIVE_SCRIPT,
  CLIP_VIZ_FORWARD_DZONE_FACEOFF_WIN_SCRIPT,
  // Goalie — 9 plays
  CLIP_VIZ_GOALIE_TRACK_AND_SAVE_SCRIPT,
  CLIP_VIZ_GOALIE_REBOUND_CONTROL_SCRIPT,
  CLIP_VIZ_GOALIE_POST_TO_POST_SCRIPT,
  CLIP_VIZ_GOALIE_BREAKAWAY_SCRIPT,
  CLIP_VIZ_GOALIE_GLOVE_FREEZE_SCRIPT,
  CLIP_VIZ_GOALIE_SCRAMBLE_SAVE_SCRIPT,
  CLIP_VIZ_GOALIE_SCREEN_TRAFFIC_SCRIPT,
  CLIP_VIZ_GOALIE_PLAY_PUCK_BREAKOUT_SCRIPT,
  CLIP_VIZ_GOALIE_PK_SEAM_SAVE_SCRIPT,
  // Guard — 8 plays
  CLIP_VIZ_GUARD_PICK_AND_ROLL_SCRIPT,
  CLIP_VIZ_GUARD_TRANSITION_PULLUP_SCRIPT,
  CLIP_VIZ_GUARD_LIVE_STEAL_SCRIPT,
  CLIP_VIZ_GUARD_DRIVE_AND_KICK_SCRIPT,
  CLIP_VIZ_GUARD_PRESS_BREAK_SCRIPT,
  CLIP_VIZ_GUARD_RUN_THE_SET_SCRIPT,
  CLIP_VIZ_GUARD_CLUTCH_FREE_THROWS_SCRIPT,
  CLIP_VIZ_GUARD_ICES_IT_LATE_SCRIPT,
  // Wing — 8 plays
  CLIP_VIZ_WING_CATCH_AND_SHOOT_SCRIPT,
  CLIP_VIZ_WING_ATTACK_CLOSEOUT_SCRIPT,
  CLIP_VIZ_WING_DENIAL_DEFLECTION_SCRIPT,
  CLIP_VIZ_WING_BACKDOOR_CUT_SCRIPT,
  CLIP_VIZ_WING_CLOSEOUT_CONTAIN_SCRIPT,
  CLIP_VIZ_WING_RELOCATE_CATCH_SHOOT_SCRIPT,
  CLIP_VIZ_WING_CLUTCH_FREE_THROWS_SCRIPT,
  CLIP_VIZ_WING_LATE_JUMPER_SCRIPT,
  // Big — 8 plays
  CLIP_VIZ_BIG_ROLL_AND_FINISH_SCRIPT,
  CLIP_VIZ_BIG_POST_SEAL_DROPSTEP_SCRIPT,
  CLIP_VIZ_BIG_BOXOUT_OUTLET_SCRIPT,
  CLIP_VIZ_BIG_RIM_PROTECT_AND_GO_SCRIPT,
  CLIP_VIZ_BIG_RESCREEN_ROLL_SCRIPT,
  CLIP_VIZ_BIG_SHORT_ROLL_READ_SCRIPT,
  CLIP_VIZ_BIG_CLUTCH_FREE_THROWS_SCRIPT,
  CLIP_VIZ_BIG_GAME_SEALING_BLOCK_SCRIPT,
];
