// Soccer positive-play VIZ library (FV-76 prerequisite wiring) — 32
// athlete-facing visualization clips: 4 position flagships (fwd/mid/def/gk)
// + 28 athlete-chooseable rehearsal scenarios, 7 per position. Authored by
// the content trio, verified against docs/soccer-module-map.md, KC prose-
// gated in docs/scripts/soccer.md. The FV-144 model: the athlete picks up
// to 3 plays and resolvePlaylist() plays them IN PLACE of the flagship
// viz-soc-{pos} clip (flagship = nothing-picked fallback). Registered in
// components/pregame/positive-plays.ts; the sport stays DORMANT (not in
// SUPPORTED_SPORTS) until the FV-78/79 go-live gate. Prose source of truth:
// docs/scripts/soccer.md ("VIZ Clips — Flagships" + "VIZ Clips — Positive
// Plays") — the book wins at render time (FV-302).
//
// Book headers point flagships at segments-soccer.ts (the football wrap
// pattern). Soccer flagships are complete 18-line clips like lacrosse, so
// they live here with the play library (FV-406 lacrosse pattern) rather
// than a third segments file. HM cells stay in clips-soccer.ts.

import type { AudioScript } from "./types";
import { SCRIPT_INSTRUCTIONS, VISUALIZATION_INSTRUCTIONS } from "./instructions.ts";
import { CLIP_LOUDNORM_FILTER } from "./loudnorm.ts";

// ── Soccer VIZ clips — position flagships ───────────────────────────────────

// Soccer · Forward · VIZ (flagship)
export const CLIP_VIZ_SOC_FWD_SCRIPT: AudioScript = {
  slug: "viz-soc-fwd",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "Keep your eyes closed. See yourself walking onto the field.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 1 },
    { type: "speech", text: "You hear the ball pinging back and forth in warmups.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 1 },
    { type: "speech", text: "Hear cleats on the field, a coach calling the group in.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You feel the field under your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.2 },
    { type: "speech", text: "Feel your shin guards settle under your socks.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.2 },
    { type: "speech", text: "Feel your cleats grip the field as you shift your weight.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You settle your breathing and prepare for the first ball forward.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 1.25 },
    { type: "speech", text: "The game starts, and you take your position on the last defender's shoulder.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 0.25 },
    { type: "speech", text: "The ball goes over the top. You time the run, stay onside, and take one touch to set it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The goalkeeper comes off the line. You open your body and pass it across into the far corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball reaches the net, and you jog back for the restart.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Next attack, the ball is driven low into the six-yard box.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get across the marker at the near post and redirect it before the keeper sets.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "See the next attack develop from wide.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You receive on the touchline, drop the shoulder, push it past the fullback, reach the byline, and cut it back into the box.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "When the ball comes into your chest instead, you take the contact, lay it off simply, and spin into the space behind.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Now visualize the next play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 0.8 },
    { type: "speech", text: "The next time they play out from the back, you press on an angle, win the ball high, and finish low from close range.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Soccer · Midfielder · VIZ (flagship)
export const CLIP_VIZ_SOC_MID_SCRIPT: AudioScript = {
  slug: "viz-soc-mid",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "Keep your eyes closed. See yourself walking onto the field.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 1 },
    { type: "speech", text: "You hear the ball pinging back and forth in warmups.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 1 },
    { type: "speech", text: "Hear cleats on the field, a coach calling the group in.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You feel the field under your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.2 },
    { type: "speech", text: "Feel your shin guards settle under your socks.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.2 },
    { type: "speech", text: "Feel your cleats grip the field as you shift your weight.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You settle your breathing and prepare for the first touch.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 1.25 },
    { type: "speech", text: "Kickoff, and you check your shoulder as the first pass comes toward you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 0.25 },
    { type: "speech", text: "You check away, come back to the ball, and open your body before it arrives.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your first touch goes out of your feet, and your head comes up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You play the pass through the line and into the forward's run.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Next possession, one side is congested. You check the far side and drive the switch into the wide player's path.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You follow your pass forward and arrive late at the top of the box.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "See the next spell of defending.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You read the pass into the forward, step into the lane before it arrives, secure the ball, and make the simple pass back into the shape.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "When the forward pass isn't there, you keep the ball, take the safe option, and move the point of attack instead of forcing it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Now visualize the next play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 0.8 },
    { type: "speech", text: "On the next possession, you receive with a presser on your back, turn out of it with one touch, and play forward into the runner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Soccer · Defender · VIZ (flagship)
export const CLIP_VIZ_SOC_DEF_SCRIPT: AudioScript = {
  slug: "viz-soc-def",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "Keep your eyes closed. See yourself walking onto the field.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 1 },
    { type: "speech", text: "You hear the ball pinging back and forth in warmups.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 1 },
    { type: "speech", text: "Hear cleats on the field, a coach calling the group in.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You feel the field under your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.2 },
    { type: "speech", text: "Feel your shin guards settle under your socks.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.2 },
    { type: "speech", text: "Feel your cleats grip the field as you shift your weight.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You settle your breathing and prepare for the first duel.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 1.25 },
    { type: "speech", text: "Kickoff, and you set your line, check your shoulder, and pick up the striker.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 0.25 },
    { type: "speech", text: "The winger runs at you with space. You manage the distance and stay on your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You show the attacker outside toward the touchline and match the next touch.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The cross gets forced early, and it's headed clear long and wide.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Next attack, the corner comes in. You pick up your mark early, attack the flight of the ball, and head it clear.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball drops to your midfielder, and the back line steps out together.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "See the next possession start from your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Their forward presses across your body and takes the inside pass away, your first touch opens you to the field, and the next pass finds the midfielder's back foot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "When the pass out isn't on, you keep it simple, put it long down the line, and hold your shape as the team steps up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Now visualize the next play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 0.8 },
    { type: "speech", text: "On another ball over the top, a runner gains half a yard behind you. You recover inside, slow the path to goal, and take the ball when the touch separates from the foot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// Soccer · Goalkeeper · VIZ (flagship)
export const CLIP_VIZ_SOC_GK_SCRIPT: AudioScript = {
  slug: "viz-soc-gk",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "Keep your eyes closed. See yourself walking onto the field.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 1 },
    { type: "speech", text: "You hear your own warmup shots being struck, the keeper coach serving the next one.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 1 },
    { type: "speech", text: "Hear cleats on the field, a coach calling the group in.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You feel the goalmouth under your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.2 },
    { type: "speech", text: "Feel your gloves close around the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.2 },
    { type: "speech", text: "Feel the straps pull snug at your wrists.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You settle your breathing and set your stance.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 1.25 },
    { type: "speech", text: "You check your posts, set your angle, and organize the back line before the first ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 0.25 },
    { type: "speech", text: "The shot comes from the edge of the box, and you are already set with your weight forward.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You move both hands through the ball and bring it into your body.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get up, scan upfield, and throw into the fullback's path to start the attack.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Next attack, the corner is swung in. You call it, come through the traffic, and take it cleanly at the top of your jump.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You land with the ball held, then get the back line reorganized.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "See the next ball played over the top.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The forward runs through, and you close the space, set as the touch comes, and smother the ball without leading into the attacker.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "When one gets past you, you retrieve the ball, get your feet moving again, and make your calls before the next ball comes.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Now visualize the next play.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 0.8 },
    { type: "speech", text: "On the next free kick, the ball comes over the wall toward your near post, and you move across and push it around the post.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
  ],
};

// ── Soccer VIZ clips — positive-play library (7 per position) ───────────────

// Soccer · Forward · VIZ — Run in behind
export const CLIP_VIZ_SOC_FWD_RUN_IN_BEHIND_SCRIPT: AudioScript = {
  slug: "viz-soc-fwd-run-in-behind",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself on the last defender's shoulder, watching the midfielder's head come up.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The center backs hold their line, and space opens behind them.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You hold your run, then start it as the pass is struck.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball goes over the top into the channel.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You're level with the last defender as the ball leaves the foot, and you stay onside.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your first touch takes the ball out of your feet and away from the recovering defender.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The goalkeeper comes off the line to narrow the angle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You keep your head steady and open your body toward the far post.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You pass the ball across the keeper and inside the far post.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The ball reaches the net, and you jog back for the restart.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Forward · VIZ — Attack the near post
export const CLIP_VIZ_SOC_FWD_NEAR_POST_FINISH_SCRIPT: AudioScript = {
  slug: "viz-soc-fwd-near-post-finish",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself at the top of the box as the ball moves wide.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The wide player looks up and pushes the ball out of the feet to cross.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You check away from your marker to buy half a yard.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The cross is driven low into the six-yard box.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You attack the near post and get across the defender's body.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You reach the ball first, in front of the marker.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You keep the contact short and redirect it before the keeper sets.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The ball changes direction and goes in at the near post.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You peel away and take your position for the restart.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Forward · VIZ — Take on the fullback
export const CLIP_VIZ_SOC_FWD_TAKE_ON_SCRIPT: AudioScript = {
  slug: "viz-soc-fwd-take-on",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself wide on the touchline, asking for the ball with space in front of you.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The pass arrives, and your first touch sets you up facing the fullback.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You run at the front foot and get the defender moving backward.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You drop your shoulder inside, then shift the ball outside.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You push it past the fullback and go.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You win the race to it with your body between the defender and the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You reach the byline and get your head up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You cut it back low, away from the keeper, into the runner at the top of the box.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The ball arrives in front of the runner, and you spin into the box for the rebound.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Forward · VIZ — Hold it up and spin
export const CLIP_VIZ_SOC_FWD_HOLD_AND_SPIN_SCRIPT: AudioScript = {
  slug: "viz-soc-fwd-hold-and-spin",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself check toward the ball with a center back tight on your back.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The long ball is played into your chest.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You turn your body sideways and take the contact without losing your balance.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your first touch settles the ball away from the defender's foot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You feel where the pressure is and hold your position with your arm across, without pushing off.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You make the simple lay-off to the midfielder arriving.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The moment the ball leaves your foot, you spin off the defender's shoulder.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You accelerate into the space behind the back line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The return ball drops in front of you, and you take it in stride toward goal.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
  ],
};

// Soccer · Forward · VIZ — Angle the press
export const CLIP_VIZ_SOC_FWD_PRESS_AND_FINISH_SCRIPT: AudioScript = {
  slug: "viz-soc-fwd-press-and-finish",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself in the front line as the keeper sets to play out.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball is rolled into the center back's feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You start your press on an angle that closes the pass inside.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You keep the run curved and shepherd the defender toward the touchline.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The next touch gets away from the defender's foot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You arrive at the right moment and take the ball cleanly.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "One touch takes you inside, and the goal opens up in front of you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You keep your head steady and side-foot it low past the keeper.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The ball goes in, and you get back into your shape for the restart.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Forward · VIZ — The penalty
export const CLIP_VIZ_SOC_FWD_PENALTY_SCRIPT: AudioScript = {
  slug: "viz-soc-fwd-penalty",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself pick up the ball and walk to the spot.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You choose your side on the walk, before you turn around.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You place the ball on the spot and press it into the turf.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You pace out your steps and set your feet the way you always do.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You breathe out once and let your shoulders drop. The keeper may move early; your side does not change.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The whistle goes, and you start your run-up at your own speed.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your plant foot lands beside the ball, pointed where you're going.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your head stays down and still through the contact.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You strike it low and hard with the inside of the foot, inside the post.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You finish through the ball and jog back to the halfway line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Forward · VIZ — Miss the sitter, get back in the match
export const CLIP_VIZ_SOC_FWD_NEXT_CHANCE_SCRIPT: AudioScript = {
  slug: "viz-soc-fwd-next-chance",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself arrive at the far post with the goal open in front of you.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The cross reaches you, and you put it over the bar from six yards.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball goes out for a goal kick.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You turn, get back into your shape, and take your position for the restart.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The next ball comes into your side, and you press on your angle as their first touch comes.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The pass gets forced backward, and you hold your position at the top.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "A few minutes later, the ball comes into your chest with a defender behind you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You take the contact, settle it, and make the simple lay-off.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The pass finds the midfielder's back foot, and the attack keeps moving.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You take your position on the last shoulder and ask for the next ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Midfielder · VIZ — Receive on the half-turn
export const CLIP_VIZ_SOC_MID_HALF_TURN_SCRIPT: AudioScript = {
  slug: "viz-soc-mid-half-turn",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself in the middle third with the ball moving across your back line.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You check away from your marker, then come back toward the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You scan before it arrives and open your body to the field.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your first touch takes the ball out of your feet, away from the pressure.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your head comes up and the line in front of you is square.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You play the pass through the gap and into the striker's run.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The ball travels forward, and the forward takes it in stride.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You continue your run to support the next ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "On a later possession, your marker follows you tighter.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You take the touch backward, keep the ball, and switch it to the open side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Midfielder · VIZ — Switch the play
export const CLIP_VIZ_SOC_MID_SWITCH_PLAY_SCRIPT: AudioScript = {
  slug: "viz-soc-mid-switch-play",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself receive in central midfield with the ball on the near side.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Both teams are compressed toward one touchline.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Before the ball arrives, you scan the far side and find the free player.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your first touch opens your hips to the field.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You take one carrying touch out of the congestion.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You strike the switch over the pressure and into space.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The ball lands in the wide player's path on the far side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Their team has to shift, and the space opens up ahead of the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You move forward into the next line to give an inside option.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The wide player attacks the space, and you support from the middle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Midfielder · VIZ — Play the ball through the line
export const CLIP_VIZ_SOC_MID_THROUGH_BALL_SCRIPT: AudioScript = {
  slug: "viz-soc-mid-through-ball",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself between the lines with your back to the center backs.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball comes into you and you take it on the half-turn.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You see the center backs square and the space behind them.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your forward starts the run across the last shoulder, staying onside.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You take one touch to set the ball on your passing foot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You weight the pass into the gap, in front of the run.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The ball rolls through the line, and the forward runs onto it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You keep moving forward to support the second ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "On the next possession, the gap closes before you can play it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You keep the ball, play the simple pass wide, and the attack restarts.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Midfielder · VIZ — Win it back in front of the back four
export const CLIP_VIZ_SOC_MID_WIN_IT_BACK_SCRIPT: AudioScript = {
  slug: "viz-soc-mid-win-it-back",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself screening the space in front of your back four.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Their midfielder has the ball and looks for the forward's feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You read the pass early and start moving before it is played.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You step into the passing lane and get your body across the forward.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You take the ball cleanly and keep it under control.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your first touch moves it away from the pressure behind you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You lift your head and find the nearest open teammate.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You make the simple pass, and your team keeps the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You return to your position in front of the back four.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The shape is set again before their next attack starts.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Midfielder · VIZ — Arrive late in the box
export const CLIP_VIZ_SOC_MID_LATE_RUN_FINISH_SCRIPT: AudioScript = {
  slug: "viz-soc-mid-late-run-finish",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself in the middle third as the ball goes wide.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The wide player takes it down the line, and you continue your run.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You time it to arrive after the defenders have turned toward the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You check your stride and find the space around the penalty spot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The cross comes in low across the box.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get your body over the ball and keep your head still.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You direct the finish on target, low and toward the far post.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The ball reaches the far corner before the keeper can get across.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You turn and jog back toward the halfway line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The game restarts, and you take your position in midfield.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Midfielder · VIZ — Turn out of the press
export const CLIP_VIZ_SOC_MID_BEAT_THE_PRESS_SCRIPT: AudioScript = {
  slug: "viz-soc-mid-beat-the-press",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself drop into your own third to receive from the keeper.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball is rolled into your feet with a presser closing on your back.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You check that shoulder before the ball arrives.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your first touch takes the ball across your body, away from the presser.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You turn out of the pressure with the ball under control.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The whole field is in front of you now.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You carry two steps forward and draw the next midfielder toward you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You release the pass to the free player before the cover arrives.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Your team moves out of its own third with the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You run forward into the next line to support the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Midfielder · VIZ — Give it away, recover the shape
export const CLIP_VIZ_SOC_MID_NEXT_TOUCH_SCRIPT: AudioScript = {
  slug: "viz-soc-mid-next-touch",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself receive in midfield and lose the ball to a challenge.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball breaks the other way, and their team moves forward.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You turn and sprint back through the middle of the field.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You pick up the runner arriving from deep and slow the attack down.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The ball is played wide, and your defense gets its shape back.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The move ends with a cross that the center back heads away.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Play continues, and you take your position in midfield again.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Later in the half, the ball comes to you in that same area.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You scan first, take it on the back foot, and play the simple pass forward.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The pass finds a teammate, and you move to support the next ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Defender · VIZ — Stand up the 1v1
export const CLIP_VIZ_SOC_DEF_ONE_V_ONE_STAND_SCRIPT: AudioScript = {
  slug: "viz-soc-def-one-v-one-stand",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself facing up the winger with space behind you and the touchline nearby.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The winger receives and turns toward you with the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You close the first few yards quickly, then slow your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You settle into a low stance about two yards off the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You angle your body to show the attacker toward the touchline.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The winger tries to come inside, and you take that side away.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The next touch goes outside, and you stay on the front foot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stay on your feet and match the run down the line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Your midfielder arrives to help, and the ball is played backward.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You recover into the back line and take your position again.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Defender · VIZ — Attack the header
export const CLIP_VIZ_SOC_DEF_WIN_THE_HEADER_SCRIPT: AudioScript = {
  slug: "viz-soc-def-win-the-header",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself in your own box as their corner is about to be taken.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You find your mark early and set your position off the shoulder.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your eyes stay on the ball as the kicker starts the run-up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball is delivered toward the near side of the six.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You start your movement early and get to the space first.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You plant, rise, and meet the ball at the top of your jump.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You attack the front of the ball and send it high, long, and wide.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The clearance leaves the box, and the line pushes out together.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You step out with the back four and pick your mark back up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The next delivery comes in, and you take that position early again.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Defender · VIZ — Read it early, step in
export const CLIP_VIZ_SOC_DEF_READ_AND_INTERCEPT_SCRIPT: AudioScript = {
  slug: "viz-soc-def-read-and-intercept",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself in the back line, watching the ball in their midfield.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Their forward drops toward the ball and asks for it into feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You read the pass before it is played and start moving.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You step in front of the forward and take the ball cleanly.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Your first touch carries you out of the crowded area.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get your head up and see the midfielder showing for it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You play the pass into the back foot, away from the pressure.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Your team moves out of the defensive third with the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You step up with the back line and hold the new position.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The shape is set, and you are ready for the next ball forward.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Defender · VIZ — Play out under pressure
export const CLIP_VIZ_SOC_DEF_PLAY_OUT_SCRIPT: AudioScript = {
  slug: "viz-soc-def-play-out",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself receive from the keeper on the edge of your own box.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Their forward presses across your body and takes the inside pass away.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You check that shoulder before the ball reaches you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Your first touch opens your body toward the field.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "That touch moves the ball across the presser's angle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You carry one step forward to commit the next defender.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You play it into the midfielder's back foot on the free side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The midfielder turns, and your team is through the first press.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You push up to support the next pass.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The back line steps out together and holds the line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Defender · VIZ — Overlap and deliver
export const CLIP_VIZ_SOC_DEF_OVERLAP_CROSS_SCRIPT: AudioScript = {
  slug: "viz-soc-def-overlap-cross",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself at fullback with your winger receiving inside of you.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The winger takes the ball toward the middle of the field.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The space outside opens up, and you start your run.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You call for it as you come past on the overlap.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The pass is played into your path down the line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You take one touch forward and get your head up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You look at the far post and see the runners arriving.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You whip the cross low across the six-yard box.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The delivery clears the first defender and reaches the far post.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You recover down the line and take your place back in the defensive line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Defender · VIZ — Recover the run, win it clean
export const CLIP_VIZ_SOC_DEF_RECOVERY_TACKLE_SCRIPT: AudioScript = {
  slug: "viz-soc-def-recovery-tackle",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See the ball played over the top with the striker running in behind.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The striker gains half a yard on you toward the goal.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You turn early and recover goal-side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You match the pace for the first strides and get level again.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "Instead of diving in, you stay on the inside shoulder and slow the path to goal.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You steer the run away from the middle and toward the corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The next touch separates from the striker's foot.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You step in front and take the ball cleanly.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You get up, scan, and play the simple pass to the nearest open teammate.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The danger is cleared, and the back line steps back into shape.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Defender · VIZ — Beaten once, reset the matchup
export const CLIP_VIZ_SOC_DEF_NEXT_DUEL_SCRIPT: AudioScript = {
  slug: "viz-soc-def-next-duel",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself defending the winger one-v-one early in the game.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The winger knocks the ball past you and gets to the byline.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The cross comes in, and your team clears it out for a corner.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You take your position for the set piece and get back into the line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Later in the half, that same matchup comes at you again.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "This time you leave a yard more space and settle your feet earlier.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "You stay patient and hold your position instead of reaching for the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The first move does not get past you, and neither does the second.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "With no way forward, the winger turns and plays the ball backward.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You step out with the line and pick the matchup back up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Goalkeeper · VIZ — Set the angle, control the shot
export const CLIP_VIZ_SOC_GK_SET_AND_SAVE_SCRIPT: AudioScript = {
  slug: "viz-soc-gk-set-and-save",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself set in the middle of your goal with the whole play in front of you.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball moves to the top of the box, and you take a step across to reset your angle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get set as the shooter's hips open, weight forward on the balls of your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The strike comes low and hard toward your right post.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Both hands move through the ball, and you bring it into your body.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You hold it clean and give up no rebound.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Later in the half, the next shot arrives high to your near side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You are set before the strike, and you push it wide of the post.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You call your marks onto the corner and re-establish your position.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "On the next ball into the box, you are set early and take it in your hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Goalkeeper · VIZ — Call it early, claim the cross
export const CLIP_VIZ_SOC_GK_CLAIM_THE_CROSS_SCRIPT: AudioScript = {
  slug: "viz-soc-gk-claim-the-cross",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself set off your line with a corner about to come in.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You take your starting position, check the traffic in front of you, and pick your path to the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball is swung toward the near post, and you read the flight early.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You call \"keeper's\" loud, before you commit.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your defenders hear it and clear the path in front of you.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You attack the ball at the top of your jump and take it cleanly out of the air.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Two hands on it, ball into your chest, and you land with it secure.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You hold it until the pressure clears, then look up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You start the counter with a throw into the wide player's path.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "On the next cross, you make the same early call and claim it again.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Goalkeeper · VIZ — Close the space on the through ball
export const CLIP_VIZ_SOC_GK_OFF_YOUR_LINE_SCRIPT: AudioScript = {
  slug: "viz-soc-gk-off-your-line",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself off your line with your back four holding a high line in front of you.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball is played over the top, and the striker turns and runs onto it.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You read it early and come off your line with your eyes on the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You close the space to the top of your box, then shorten your steps as the touch comes.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The touch runs long, and you commit.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get down behind the ball inside your box, hands first, and take it before the shot comes.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You bring it into your body and stay over it until you're up and covered.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You get up, look up, and roll it out to the fullback in space.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You call your line to step up and squeeze the field again.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You reset your starting position, ready for the next ball over the top.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Goalkeeper · VIZ — Collect it, start the next attack
export const CLIP_VIZ_SOC_GK_DISTRIBUTION_SCRIPT: AudioScript = {
  slug: "viz-soc-gk-distribution",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself with the ball in your hands and the whole field open in front of you.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You gather a routine shot cleanly and hold it, scanning upfield while their press sets.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The short option is covered, so you take two steps and look wide.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You pick out the fullback pushing high on your side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You throw it flat into the fullback's path, past the first line of pressure.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The ball arrives in stride, the team moves forward, and you push out to the edge of your box.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Later, a back pass comes to your feet with a striker closing you down.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "Your first touch takes the ball out of your feet and opens your body.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You play the simple pass into the center back, who's free and facing the field.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The shape moves up the field, and you return to your position and organize the line.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Goalkeeper · VIZ — Set the wall, save the free kick
export const CLIP_VIZ_SOC_GK_WALL_AND_FREEKICK_SCRIPT: AudioScript = {
  slug: "viz-soc-gk-wall-and-freekick",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself organizing your wall with a free kick just outside the box.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You take your position by the post quickly, look down the line of the ball, and set your wall.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You point, count the players out loud, and move the wall a step until the near post is covered.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You send your wall-setter out and take your position where you can see the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get set as the run-up starts, weight forward, eyes on the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The strike goes up and over the wall toward your side.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You push off hard, get a strong hand to it, and turn it around the post.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 3 },
    { type: "speech", text: "The corner is coming, so you set your feet and re-organize your marks.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You take the next ball out of the air and hold it in your hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Goalkeeper · VIZ — Set on the line, read the strike
export const CLIP_VIZ_SOC_GK_PENALTY_SAVE_SCRIPT: AudioScript = {
  slug: "viz-soc-gk-penalty-save",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself on your line as the ball is placed on the spot.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You take your time, set your feet on the line, and settle your breathing.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You watch the walk-back and pick up the angle of the run-up.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You stay still and set as the run-up begins, weight on the balls of your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You keep your eyes on the ball and wait for the strike instead of guessing early.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The shooter opens the body and strikes toward your left.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You load the outside leg and drive both hands toward the ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get a firm hand on it and push it out low, away from the middle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get straight back up and set your feet for the second ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The ball is cleared, and you call your line back into shape.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// Soccer · Goalkeeper · VIZ — Soft goal, reset for the next shot
export const CLIP_VIZ_SOC_GK_NEXT_SAVE_SCRIPT: AudioScript = {
  slug: "viz-soc-gk-next-save",
  voice: "ash",
  instructions: SCRIPT_INSTRUCTIONS,
  speed: 1.1,
  postFilter: CLIP_LOUDNORM_FILTER,
  segments: [
    { type: "speech", text: "See yourself picking the ball out of your net after a shot you expected to save.", instructions: VISUALIZATION_INSTRUCTIONS, mark: { phase: "rink" } },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "The goal counts. You hand the ball off for the restart.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You take the walk back to your line and reset your feet.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "The game restarts from the center circle, and you re-establish your position and your angle.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You make the calls your back line needs: who has the runner, and where the pressure is coming from.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "Play comes back toward you, and the next shot arrives from the edge of the box.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get set early, hands ready, and track the ball all the way into your body.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "It is an ordinary save, held cleanly, and the ball stays in your hands.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
    { type: "speech", text: "You get up, look up, and roll it out to the closest option.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2 },
    { type: "speech", text: "You return to your position and set for the next ball.", instructions: VISUALIZATION_INSTRUCTIONS },
    { type: "silence", durationSec: 2.5 },
  ],
};

// ── Exports ───────────────────────────────────────────────────────────────

export const SOCCER_VIZ_CLIP_SCRIPTS: AudioScript[] = [
  CLIP_VIZ_SOC_FWD_SCRIPT,
  CLIP_VIZ_SOC_MID_SCRIPT,
  CLIP_VIZ_SOC_DEF_SCRIPT,
  CLIP_VIZ_SOC_GK_SCRIPT,
  CLIP_VIZ_SOC_FWD_RUN_IN_BEHIND_SCRIPT,
  CLIP_VIZ_SOC_FWD_NEAR_POST_FINISH_SCRIPT,
  CLIP_VIZ_SOC_FWD_TAKE_ON_SCRIPT,
  CLIP_VIZ_SOC_FWD_HOLD_AND_SPIN_SCRIPT,
  CLIP_VIZ_SOC_FWD_PRESS_AND_FINISH_SCRIPT,
  CLIP_VIZ_SOC_FWD_PENALTY_SCRIPT,
  CLIP_VIZ_SOC_FWD_NEXT_CHANCE_SCRIPT,
  CLIP_VIZ_SOC_MID_HALF_TURN_SCRIPT,
  CLIP_VIZ_SOC_MID_SWITCH_PLAY_SCRIPT,
  CLIP_VIZ_SOC_MID_THROUGH_BALL_SCRIPT,
  CLIP_VIZ_SOC_MID_WIN_IT_BACK_SCRIPT,
  CLIP_VIZ_SOC_MID_LATE_RUN_FINISH_SCRIPT,
  CLIP_VIZ_SOC_MID_BEAT_THE_PRESS_SCRIPT,
  CLIP_VIZ_SOC_MID_NEXT_TOUCH_SCRIPT,
  CLIP_VIZ_SOC_DEF_ONE_V_ONE_STAND_SCRIPT,
  CLIP_VIZ_SOC_DEF_WIN_THE_HEADER_SCRIPT,
  CLIP_VIZ_SOC_DEF_READ_AND_INTERCEPT_SCRIPT,
  CLIP_VIZ_SOC_DEF_PLAY_OUT_SCRIPT,
  CLIP_VIZ_SOC_DEF_OVERLAP_CROSS_SCRIPT,
  CLIP_VIZ_SOC_DEF_RECOVERY_TACKLE_SCRIPT,
  CLIP_VIZ_SOC_DEF_NEXT_DUEL_SCRIPT,
  CLIP_VIZ_SOC_GK_SET_AND_SAVE_SCRIPT,
  CLIP_VIZ_SOC_GK_CLAIM_THE_CROSS_SCRIPT,
  CLIP_VIZ_SOC_GK_OFF_YOUR_LINE_SCRIPT,
  CLIP_VIZ_SOC_GK_DISTRIBUTION_SCRIPT,
  CLIP_VIZ_SOC_GK_WALL_AND_FREEKICK_SCRIPT,
  CLIP_VIZ_SOC_GK_PENALTY_SAVE_SCRIPT,
  CLIP_VIZ_SOC_GK_NEXT_SAVE_SCRIPT,
];
