/**
 * From Victory — Service Worker route → cache-strategy decision (FV-126).
 *
 * This is the PURE, side-effect-free extraction of the request-routing logic
 * that lives inline in `apps/web/public/sw.js`'s `fetch` handler. It maps a
 * request (origin + pathname + navigate flag) to the cache strategy that the
 * service worker applies.
 *
 * WHY THIS EXISTS AS A SEPARATE MODULE
 * ------------------------------------
 * `public/sw.js` is a hand-rolled, static service worker (registered directly
 * as `/sw.js` — see ServiceWorkerRegistrar.tsx). It is NOT generated by a build
 * step and it CANNOT `import` from TypeScript at runtime (same constraint that
 * forces `MANIFEST_VERSION` to be duplicated between `audio-mapping.ts` and
 * `sw.js`). So this module is the single, unit-tested source of truth for the
 * routing DECISION; `sw.js` mirrors the exact same branch order in its `fetch`
 * handler. The sync test (`__tests__/sw-route-strategy.test.ts`) reads the real
 * `sw.js` source and asserts the runtime copy stays equivalent to this function,
 * so the two can never silently drift.
 *
 * BEHAVIOR CONTRACT (must match sw.js exactly — this is a pure refactor)
 * ---------------------------------------------------------------------
 * Branch order, mirrored 1:1 from sw.js `fetch`:
 *   0.  cross-origin                         → "passthrough"  (never intercepted)
 *   1a. /audio/pregame/*                     → "audio-cache-first"
 *   1a-ii. /audio/beds/*                     → "audio-cache-first"
 *   1b. /athlete/pregame (and trailing "/")  → "pregame-shell-network-first"
 *   1c. bypass list                          → "passthrough"  (always network)
 *       (/api/, /auth/, /athlete, /dashboard/, /pair, /signin, /signup,
 *        /forgot-, /reset-, /subscribe, /audio/)
 *   2.  /_next/static/*                       → "cache-first"
 *   3.  icon/font file extensions             → "cache-first"
 *   4.  navigation requests (mode: navigate)  → "network-first-offline-fallback"
 *   5.  everything else                       → "passthrough"
 *
 * NOTE on ordering vs. the bypass list: `/athlete/pregame` (1b) is checked
 * BEFORE the `/athlete` prefix bypass (1c) on purpose — pregame is the one
 * authenticated path that gets a cache strategy; every other `/athlete/*`
 * route falls through to the network and is never cached. Likewise
 * `/audio/pregame/*` and `/audio/beds/*` (1a / 1a-ii) are checked before the
 * `/audio/` bypass prefix (1c) so they reach the audio cache while all other
 * `/audio/*` paths fall through.
 */

/**
 * The set of strategies the service worker can apply to a request.
 *
 * - `audio-cache-first`            → `audioCacheFirst()` in sw.js
 * - `pregame-shell-network-first`  → `pregameShellNetworkFirst()` in sw.js
 * - `cache-first`                  → `cacheFirst()` in sw.js
 * - `network-first-offline-fallback` → `networkFirstWithOfflineFallback()` in sw.js
 * - `passthrough`                  → no `respondWith` — the browser's default
 *                                    network fetch handles it (never cached)
 */
export type SwStrategy =
  | "audio-cache-first"
  | "pregame-shell-network-first"
  | "cache-first"
  | "network-first-offline-fallback"
  | "passthrough";

/**
 * The pregame offline-shell path. Mirrors `PREGAME_PATH` in sw.js.
 * `/athlete/pregame` is the ONLY authenticated path with a cache strategy.
 */
export const PREGAME_PATH = "/athlete/pregame";

/**
 * Same-origin path prefixes that ALWAYS go to the network and are NEVER cached.
 * Mirrors the section "1c. NEVER cache — always network" disjunction in sw.js.
 *
 * Order within this list does not affect the decision (it's a logical OR of
 * `pathname.startsWith(prefix)`), but it is kept identical to sw.js for
 * auditability.
 *
 * `/athlete` (no trailing slash) is intentional: it bypasses /athlete itself
 * and every /athlete/* page EXCEPT /athlete/pregame, which is handled earlier.
 */
export const BYPASS_PREFIXES = [
  "/api/",
  "/auth/",
  "/athlete",
  "/dashboard/",
  "/pair",
  "/signin",
  "/signup",
  "/forgot-",
  "/reset-",
  "/subscribe",
  "/audio/",
] as const;

/**
 * File-extension test for brand assets served cache-first (icons + fonts).
 * Mirrors the `isIconOrFont` regex in sw.js section 3.
 *
 * Exported (and a fresh RegExp per module load, not a shared stateful literal)
 * so tests can assert against the exact pattern. The pattern has no global
 * flag, so there is no `lastIndex` statefulness to worry about.
 */
export const ICON_OR_FONT_RE = /\.(png|svg|ico|webmanifest|woff2|woff|ttf|otf)$/;

/**
 * Inputs to the routing decision. These are the minimal facts sw.js derives
 * from the `FetchEvent` (`event.request` + `new URL(request.url)`):
 *
 * - `pathname`   → `url.pathname`
 * - `isSameOrigin` → `url.origin === self.location.origin`
 * - `isNavigate` → `request.mode === "navigate"`
 *
 * Method (GET/HEAD) is intentionally NOT an input: in sw.js the HEAD handling
 * lives INSIDE `audioCacheFirst`, not in the routing decision — a HEAD probe to
 * `/audio/pregame/*` still routes to `audio-cache-first`. Keeping method out of
 * this function preserves that and keeps the decision purely path-based.
 */
export interface SwRouteInput {
  /** The request URL's pathname, e.g. "/athlete/pregame". */
  pathname: string;
  /** `url.origin === self.location.origin` in the SW. */
  isSameOrigin: boolean;
  /** `request.mode === "navigate"`. */
  isNavigate: boolean;
}

/**
 * Decide which cache strategy applies to a request.
 *
 * Pure: no side effects, no SW globals, no `caches`/`fetch`/`self`. Safe to
 * import and exercise in vitest. The branch order is a 1:1 mirror of the
 * `fetch` handler in `public/sw.js` — see the BEHAVIOR CONTRACT above. Any
 * change here MUST be mirrored in sw.js (the sync test enforces equivalence).
 */
export function decideStrategy(input: SwRouteInput): SwStrategy {
  const { pathname, isSameOrigin, isNavigate } = input;

  // 0. cross-origin — never intercepted (sw.js returns early before respondWith).
  if (!isSameOrigin) {
    return "passthrough";
  }

  // 1a. Pregame audio — cache-first in the audio cache (FV-106).
  if (pathname.startsWith("/audio/pregame/")) {
    return "audio-cache-first";
  }

  // 1a-ii. Music beds — cache-first in the SAME audio cache (FV-227).
  if (pathname.startsWith("/audio/beds/")) {
    return "audio-cache-first";
  }

  // 1b. Pregame shell — network-first, cache the PII-free shell (FV-107).
  // Checked BEFORE the /athlete bypass below so pregame gets its strategy.
  if (pathname === PREGAME_PATH || pathname === PREGAME_PATH + "/") {
    return "pregame-shell-network-first";
  }

  // 1c. NEVER cache — always network (passthrough). Logical OR of prefixes.
  for (const prefix of BYPASS_PREFIXES) {
    if (pathname.startsWith(prefix)) {
      return "passthrough";
    }
  }

  // 2. Static build assets — cache-first (content-addressed by Next.js).
  if (pathname.startsWith("/_next/static/")) {
    return "cache-first";
  }

  // 3. Brand asset files (icons + fonts) — cache-first.
  if (ICON_OR_FONT_RE.test(pathname)) {
    return "cache-first";
  }

  // 4. Navigation requests — network-first with offline fallback.
  if (isNavigate) {
    return "network-first-offline-fallback";
  }

  // 5. Everything else (non-cacheable JS chunks, etc.) — passthrough.
  return "passthrough";
}
