-- =============================================================================
-- Migration: 20260611140000_parent_digest_preferences.sql
--
-- Purpose:
--   Adds opt-out preference for the weekly parent digest email (FV-226).
--
--   Two new columns on public.profiles:
--     digest_opt_out       — boolean, default false. When true the weekly
--                            digest cron skips this parent. Parent rows only;
--                            athlete rows stay null (constraint below).
--     digest_unsubscribe_token — random UUID used as a one-click unsubscribe
--                            token embedded in every digest email. Generated
--                            once at row-creation time via service-role action
--                            (or backfilled here for existing parents via a
--                            DO block). Null on athlete rows.
--
-- Privacy model:
--   - No new table; no new RLS policies needed.
--   - The columns live on profiles. The existing `profiles_update_own` policy
--     already allows a parent to update their own row, which covers the
--     settings toggle (digest_opt_out). The service-role server action that
--     handles the toggle re-derives the user id from the session — no client-
--     trusted id.
--   - digest_unsubscribe_token is readable by the parent via `profiles_select_own`
--     (parent reads their own row) and is NOT exposed on the athlete-facing
--     surface. The cron route reads it via service-role only.
--   - The token is a UUID — not a JWT, not derivable from public data. It is
--     validated by the unsubscribe route before accepting an opt-out change.
--   - Columns are constrained to null on athlete rows (same pattern as birthdate
--     on parent rows) so the schema reflects the intent.
--
-- Cascading delete: both columns live on profiles, which already cascades from
--   auth.users. No additional FK work needed.
--
-- RLS: no new enable or policies — the existing profiles policies cover this.
--   Verified:
--     profiles_select_own       — parent reads own row (token included)
--     profiles_update_own       — parent updates own row (opt-out toggle)
--     profiles_parent_select_linked_athlete — parent reads athlete rows (no token there)
--
-- Postgres version: 15+
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Add digest_opt_out column (parent rows only)
-- ---------------------------------------------------------------------------

alter table public.profiles
  add column if not exists digest_opt_out boolean
    default false;

comment on column public.profiles.digest_opt_out is
  'When true, this parent does not receive the weekly rhythm digest email. '
  'Null on athlete rows (constraint below). Set via the settings toggle or the '
  'unsubscribe link in the email. Default false = opted in.';

-- ---------------------------------------------------------------------------
-- 2. Add digest_unsubscribe_token column (parent rows only)
-- ---------------------------------------------------------------------------

alter table public.profiles
  add column if not exists digest_unsubscribe_token uuid
    default null;

comment on column public.profiles.digest_unsubscribe_token is
  'One-time-use-forever UUID embedded in every digest email as an unsubscribe '
  'link token. Null on athlete rows. Generated by the service-role server action '
  'when the parent first opts in or on first email send. Treated as a secret — '
  'never logged, never exposed in client responses.';

-- ---------------------------------------------------------------------------
-- 3. Constraint: both columns must be null on athlete rows
--    (extending the existing birthdate_role_consistency pattern)
-- ---------------------------------------------------------------------------

alter table public.profiles
  add constraint digest_prefs_role_consistency
    check (
      (role = 'athlete' and digest_opt_out is null and digest_unsubscribe_token is null)
      or
      (role = 'parent')
    );

-- ---------------------------------------------------------------------------
-- 4. Backfill: give every existing parent row a token so the cron can send
--    immediately after this migration lands. New parent rows get the token
--    stamped by the service-role action on first digest send.
-- ---------------------------------------------------------------------------

do $$
begin
  update public.profiles
     set digest_unsubscribe_token = gen_random_uuid()
   where role = 'parent'
     and digest_unsubscribe_token is null;
end;
$$;

-- ---------------------------------------------------------------------------
-- 5. Backfill: set digest_opt_out = false on existing parent rows where it
--    landed as null (add column with default doesn't backfill null rows in
--    Postgres when add column if not exists is used on an existing column).
-- ---------------------------------------------------------------------------

update public.profiles
   set digest_opt_out = false
 where role = 'parent'
   and digest_opt_out is null;
